
		
//========================================================================
// This file was generated using the MyGeneration tool in combination
// with the Gentle.NET Business Entity template, $Rev: 44c $
//========================================================================
using System;
using System.Collections;
using Gentle.Framework;

namespace Rainbow.Data.GentleNET
{
	#region rb_GeneralModuleDefinitions
	/// <summary>
	/// This object represents the properties and methods of a Employee.
	/// </summary>
	[Serializable]
	[TableName("rb_GeneralModuleDefinitions")]
	public class rb_GeneralModuleDefinitions : Persistent
	{
		#region Members
		private bool _changed = false;
		private static bool invalidatedListAll = true;
		private static ArrayList listAllCache = null;
		[TableColumn("GeneralModDefID", NotNull=true), PrimaryKey(AutoGenerated=false)]
		protected Guid generalModDefID;
		[TableColumn("FriendlyName", NotNull=true)]
		protected string friendlyName;
		[TableColumn("DesktopSrc", NotNull=true)]
		protected string desktopSrc;
		[TableColumn("MobileSrc", NotNull=true)]
		protected string mobileSrc;
		[TableColumn("AssemblyName", NotNull=true)]
		protected string assemblyName;
		[TableColumn("ClassName")]
		protected string className;
		[TableColumn("Admin")]
		protected bool admin;
		[TableColumn("Searchable")]
		protected bool searchable;
		#endregion
			

		#region Constructors
	

		/// <summary> 
		/// Create a new object using the minimum required information (all not-null fields except 
		/// auto-generated primary keys). 
		/// </summary> 
		public rb_GeneralModuleDefinitions( 
				Guid GeneralModDefID, 
				string FriendlyName, 
				string DesktopSrc, 
				string MobileSrc, 
				string AssemblyName)
		{
			_changed = true;
			invalidatedListAll = true;
			generalModDefID = GeneralModDefID;
			friendlyName = FriendlyName;
			desktopSrc = DesktopSrc;
			mobileSrc = MobileSrc;
			assemblyName = AssemblyName;
		}

			
		/// <summary> 
		/// Create an object from an existing row of data. This will be used by Gentle to 
		/// construct objects from retrieved rows. 
		/// </summary> 
		public rb_GeneralModuleDefinitions( 
				Guid GeneralModDefID, 
				string FriendlyName, 
				string DesktopSrc, 
				string MobileSrc, 
				string AssemblyName, 
				string ClassName, 
				bool Admin, 
				bool Searchable)
		{
			generalModDefID = GeneralModDefID;
			friendlyName = FriendlyName;
			desktopSrc = DesktopSrc;
			mobileSrc = MobileSrc;
			assemblyName = AssemblyName;
			className = ClassName;
			admin = Admin;
			searchable = Searchable;
		}

		#endregion

		#region Public Properties
		
		public bool Changed
		{ get { return _changed; } }
		
		public Guid GeneralModDefID
		{
			get{ return generalModDefID; }
			set{ _changed |= generalModDefID != value; generalModDefID = value; invalidatedListAll =  _changed;}
		}
		
		public string FriendlyName
		{
			get{ return friendlyName != null ?friendlyName.TrimEnd() : null; }
			set{ _changed |= friendlyName != value; friendlyName = value; invalidatedListAll =  _changed;}
		}
		
		public string DesktopSrc
		{
			get{ return desktopSrc != null ?desktopSrc.TrimEnd() : null; }
			set{ _changed |= desktopSrc != value; desktopSrc = value; invalidatedListAll =  _changed;}
		}
		
		public string MobileSrc
		{
			get{ return mobileSrc != null ?mobileSrc.TrimEnd() : null; }
			set{ _changed |= mobileSrc != value; mobileSrc = value; invalidatedListAll =  _changed;}
		}
		
		public string AssemblyName
		{
			get{ return assemblyName != null ?assemblyName.TrimEnd() : null; }
			set{ _changed |= assemblyName != value; assemblyName = value; invalidatedListAll =  _changed;}
		}
		
		public string ClassName
		{
			get{ return className != null ?className.TrimEnd() : null; }
			set{ _changed |= className != value; className = value; invalidatedListAll =  _changed;}
		}
		
		public bool Admin
		{
			get{ return admin; }
			set{ _changed |= admin != value; admin = value; invalidatedListAll =  _changed;}
		}
		
		public bool Searchable
		{
			get{ return searchable; }
			set{ _changed |= searchable != value; searchable = value; invalidatedListAll =  _changed;}
		}
		
	
		// generate a static property to retrieve all instances of a class that are stored in the database
		static public IList ListAll
		{
			get 
			{ 
				if( listAllCache == null || invalidatedListAll )
				{
					listAllCache = Broker.RetrieveList( typeof(rb_GeneralModuleDefinitions) ) as ArrayList;
					invalidatedListAll = false;
				}
				return listAllCache;
			}
		}
		
		#endregion

		#region Debug Properties
		/// <summary>
		/// Generated only when genDebug flag enabled in MyGeneration template UI
		/// Returns number of items in internal cache
		/// </summary>
		public static int CacheCount
		{
			get{ return listAllCache == null ? 0 : listAllCache.Count;}
		}
		
		#endregion

		#region Storage and retrieval
	   
		public static rb_GeneralModuleDefinitions Retrieve(Guid id )
		{
		  
			Key key = new Key( typeof(rb_GeneralModuleDefinitions), true, "GeneralModDefID", id );
			return Broker.RetrieveInstance( typeof(rb_GeneralModuleDefinitions), key ) as rb_GeneralModuleDefinitions;
		}

		//Gentle.NET Business Entity script: Generation of complex retrieve function (multiple primary keys) is not implemented yet.

		public override void Persist()
		{
			if( Changed || !IsPersisted )
			{
				base.Persist();
				_changed=false;
			}
		}

		public override void Remove()
		{
			base.Remove();
			invalidatedListAll = true;
		}
		#endregion

		#region Relations
		// List of primary keys for this class table
		// Key: GeneralModDefID
		// List of foreign keys for this class table
		// Key: FK_rbContentManager_GenModDefs primary table: rb_GeneralModuleDefinitions primary column: GeneralModDefID foreign column: GeneralModDefID foreign table: rb_ContentManager
		// Key: FK_rb_ModuleDefinitions_rb_GeneralModuleDefinitions primary table: rb_GeneralModuleDefinitions primary column: GeneralModDefID foreign column: GeneralModDefID foreign table: rb_ModuleDefinitions
		// Key: FK_rb_SolutionModuleDefinitions_rb_GeneralModuleDefinitions primary table: rb_GeneralModuleDefinitions primary column: GeneralModDefID foreign column: GeneralModDefID foreign table: rb_SolutionModuleDefinitions
		// List of selected relation tables for this database
		// Table: rb_Announcements
		// Table: rb_Announcements_st
		// Table: rb_Articles
		// Table: rb_Blacklist
		// Table: rb_BlogComments
		// Table: rb_Blogs
		// Table: rb_BlogStats
		// Table: rb_BookList
		// Table: rb_ComponentModule
		// Table: rb_Contacts
		// Table: rb_Contacts_st
		// Table: rb_ContentManager
		// Table: rb_Countries
		// Table: rb_Cultures
		// Table: rb_Discussion
		// Table: rb_Documents
		// Table: rb_Documents_st
		// Table: rb_EnhancedHtml
		// Table: rb_EnhancedHtml_st
		// Table: rb_EnhancedLinks
		// Table: rb_EnhancedLinks_st
		// Table: rb_Events
		// Table: rb_Events_st
		// Table: rb_FAQs
		// Table: rb_GeneralModuleDefinitions
		// Table: rb_HtmlText
		// Table: rb_HtmlText_st
		// Table: rb_Links
		// Table: rb_Links_st
		// Table: rb_Localize
		// Table: rb_Milestones
		// Table: rb_Milestones_st
		// Table: rb_ModuleDefinitions
		// Table: rb_Modules
		// Table: rb_ModuleSettings
		// Table: rb_Monitoring
		// Table: rb_Pictures
		// Table: rb_Pictures_st
		// Table: rb_Portals
		// Table: rb_PortalSettings
		// Table: rb_Roles
		// Table: rb_SolutionModuleDefinitions
		// Table: rb_Solutions
		// Table: rb_States
		// Table: rb_SurveyAnswers
		// Table: rb_SurveyOptions
		// Table: rb_SurveyQuestions
		// Table: rb_Surveys
		// Table: rb_Tabs
		// Table: rb_TabSettings
		// Table: rb_Tasks
		// Table: rb_UserDefinedData
		// Table: rb_UserDefinedFields
		// Table: rb_UserDefinedRows
		// Table: rb_UserDesktop
		// Table: rb_UserRoles
		// Table: rb_Users
		// Table: rb_Versions

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Modules", using relation table "rb_ModuleDefinitions"
		/// </summary>
		public IList referencedrb_ModulesUsingrb_ModuleDefinitions()
		{
			return new GentleList( typeof(rb_Modules), this, typeof(rb_ModuleDefinitions));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Solutions", using relation table "rb_SolutionModuleDefinitions"
		/// </summary>
		public IList referencedrb_SolutionsUsingrb_SolutionModuleDefinitions()
		{
			return new GentleList( typeof(rb_Solutions), this, typeof(rb_SolutionModuleDefinitions));
		}
		#endregion

		#region ManualCode
/***PRESERVE_BEGIN MANUAL_CODE***//***PRESERVE_END MANUAL_CODE***/
		#endregion
	}

}
#endregion


