
		
//========================================================================
// This file was generated using the MyGeneration tool in combination
// with the Gentle.NET Business Entity template, $Rev: 44 $
//========================================================================
using System;
using System.Collections;
using Gentle.Framework;

namespace Rainbow.Data.GentleNET
{
	#region rb_Portals
	/// <summary>
	/// This object represents the properties and methods of a Employee.
	/// </summary>
	[Serializable]
	[TableName("rb_Portals")]
	public class rb_Portals : Persistent
	{
		#region Members
		private bool _changed = false;
		private static bool invalidatedListAll = true;
		private static ArrayList listAllCache = null;
		[TableColumn("PortalID", NotNull=true), PrimaryKey(AutoGenerated=true)]
		protected int portalID;
		[TableColumn("PortalAlias", NotNull=true)]
		protected string portalAlias;
		[TableColumn("PortalName", NotNull=true)]
		protected string portalName;
		[TableColumn("PortalPath")]
		protected string portalPath;
		[TableColumn("AlwaysShowEditButton", NotNull=true)]
		protected bool alwaysShowEditButton;
		#endregion

		#region Constructors
	

		/// <summary> 
		/// Create a new object using the minimum required information (all not-null fields except 
		/// auto-generated primary keys). 
		/// </summary> 
		public rb_Portals( 
				string PortalAlias, 
				string PortalName, 
				bool AlwaysShowEditButton)
		{
			_changed = true;
			invalidatedListAll = true;
			portalID = 0;
			portalAlias = PortalAlias;
			portalName = PortalName;
			alwaysShowEditButton = AlwaysShowEditButton;
		}


		/// <summary> 
		/// Create a new object by specifying all fields (except the auto-generated primary key field). 
		/// </summary> 
		public rb_Portals( 
				string PortalAlias, 
				string PortalName, 
				string PortalPath, 
				bool AlwaysShowEditButton)
		{
			_changed = true;
			invalidatedListAll = true;
			portalAlias = PortalAlias;
			portalName = PortalName;
			portalPath = PortalPath;
			alwaysShowEditButton = AlwaysShowEditButton;
		}

			
		/// <summary> 
		/// Create an object from an existing row of data. This will be used by Gentle to 
		/// construct objects from retrieved rows. 
		/// </summary> 
		public rb_Portals( 
				int PortalID, 
				string PortalAlias, 
				string PortalName, 
				string PortalPath, 
				bool AlwaysShowEditButton)
		{
			portalID = PortalID;
			portalAlias = PortalAlias;
			portalName = PortalName;
			portalPath = PortalPath;
			alwaysShowEditButton = AlwaysShowEditButton;
		}

		#endregion

		#region Public Properties
		
		public bool Changed
		{ get { return _changed; } }
		
		public int PortalID
		{
			get{ return portalID; }
		}
		
		public string PortalAlias
		{
			get{ return portalAlias != null ?portalAlias.TrimEnd() : null; }
			set{ _changed |= portalAlias != value; portalAlias = value; invalidatedListAll =  _changed;}
		}
		
		public string PortalName
		{
			get{ return portalName != null ?portalName.TrimEnd() : null; }
			set{ _changed |= portalName != value; portalName = value; invalidatedListAll =  _changed;}
		}
		
		public string PortalPath
		{
			get{ return portalPath != null ?portalPath.TrimEnd() : null; }
			set{ _changed |= portalPath != value; portalPath = value; invalidatedListAll =  _changed;}
		}
		
		public bool AlwaysShowEditButton
		{
			get{ return alwaysShowEditButton; }
			set{ _changed |= alwaysShowEditButton != value; alwaysShowEditButton = value; invalidatedListAll =  _changed;}
		}
		
	
		// generate a static property to retrieve all instances of a class that are stored in the database
		static public IList ListAll
		{
			get 
			{ 
				if( listAllCache == null || invalidatedListAll )
				{
					listAllCache = Broker.RetrieveList( typeof(rb_Portals) ) as ArrayList;
					invalidatedListAll = false;
				}
				return listAllCache;
			}
		}
		
		#endregion

		#region Debug Properties
		/// <summary>
		/// Generated only when genDebug flag enabled in MyGeneration template UI
		/// Returns number of items in internal cache
		/// </summary>
		public static int CacheCount
		{
			get{ return listAllCache == null ? 0 : listAllCache.Count;}
		}
		
		#endregion

		#region Storage and retrieval
	   
		public static rb_Portals Retrieve(int id )
		{
	   
			// Return null if id is smaller than seed and/or increment for autokey
			if(id<0) 
			{
				return null;
			}
		  
			Key key = new Key( typeof(rb_Portals), true, "PortalID", id );
			return Broker.RetrieveInstance( typeof(rb_Portals), key ) as rb_Portals;
		}

		//Gentle.NET Business Entity script: Generation of complex retrieve function (multiple primary keys) is not implemented yet.

		public override void Persist()
		{
			if( Changed || !IsPersisted )
			{
				base.Persist();
				_changed=false;
			}
		}

		public override void Remove()
		{
			base.Remove();
			invalidatedListAll = true;
		}
		#endregion

		#region Relations
		// List of primary keys for this class table
		// Key: PortalID
		// List of foreign keys for this class table
		// Key: FK_rb_PortalSettings_rb_Portals primary table: rb_Portals primary column: PortalID foreign column: PortalID foreign table: rb_PortalSettings
		// Key: FK_rb_Roles_rb_Portals primary table: rb_Portals primary column: PortalID foreign column: PortalID foreign table: rb_Roles
		// Key: FK_rb_Users_rb_Portals primary table: rb_Portals primary column: PortalID foreign column: PortalID foreign table: rb_Users
		// List of selected relation tables for this database
		// Table: rb_Announcements
		// Table: rb_Announcements_st
		// Table: rb_Articles
		// Table: rb_Blacklist
		// Table: rb_BlogComments
		// Table: rb_Blogs
		// Table: rb_BlogStats
		// Table: rb_BookList
		// Table: rb_ComponentModule
		// Table: rb_Contacts
		// Table: rb_Contacts_st
		// Table: rb_ContentManager
		// Table: rb_Countries
		// Table: rb_Cultures
		// Table: rb_Discussion
		// Table: rb_Documents
		// Table: rb_Documents_st
		// Table: rb_EnhancedHtml
		// Table: rb_EnhancedHtml_st
		// Table: rb_EnhancedLinks
		// Table: rb_EnhancedLinks_st
		// Table: rb_Events
		// Table: rb_Events_st
		// Table: rb_FAQs
		// Table: rb_GeneralModuleDefinitions
		// Table: rb_HtmlText
		// Table: rb_HtmlText_st
		// Table: rb_Links
		// Table: rb_Links_st
		// Table: rb_Localize
		// Table: rb_Milestones
		// Table: rb_Milestones_st
		// Table: rb_ModuleDefinitions
		// Table: rb_Modules
		// Table: rb_ModuleSettings
		// Table: rb_Monitoring
		// Table: rb_Pictures
		// Table: rb_Pictures_st
		// Table: rb_Portals
		// Table: rb_PortalSettings
		// Table: rb_Roles
		// Table: rb_SolutionModuleDefinitions
		// Table: rb_Solutions
		// Table: rb_States
		// Table: rb_SurveyAnswers
		// Table: rb_SurveyOptions
		// Table: rb_SurveyQuestions
		// Table: rb_Surveys
		// Table: rb_Tabs
		// Table: rb_TabSettings
		// Table: rb_Tasks
		// Table: rb_UserDefinedData
		// Table: rb_UserDefinedFields
		// Table: rb_UserDefinedRows
		// Table: rb_UserDesktop
		// Table: rb_UserRoles
		// Table: rb_Users
		// Table: rb_Versions

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserRoles", using relation table "rb_Roles"
		/// </summary>
		public IList referencedrb_UserRolesUsingrb_Roles()
		{
			return new GentleList( typeof(rb_UserRoles), this, typeof(rb_Roles));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserDesktop", using relation table "rb_Users"
		/// </summary>
		public IList referencedrb_UserDesktopUsingrb_Users()
		{
			return new GentleList( typeof(rb_UserDesktop), this, typeof(rb_Users));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserRoles", using relation table "rb_Users"
		/// </summary>
		public IList referencedrb_UserRolesUsingrb_Users()
		{
			return new GentleList( typeof(rb_UserRoles), this, typeof(rb_Users));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Countries", using relation table "rb_Users"
		/// </summary>
		public IList referencedrb_CountriesUsingrb_Users()
		{
			return new GentleList( typeof(rb_Countries), this, typeof(rb_Users));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_States", using relation table "rb_Users"
		/// </summary>
		public IList referencedrb_StatesUsingrb_Users()
		{
			return new GentleList( typeof(rb_States), this, typeof(rb_Users));
		}
		#endregion

		#region ManualCode
/***PRESERVE_BEGIN MANUAL_CODE***/
		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Tabs", using relation table "rb_Portals"
		/// </summary>
		public IList referencedrb_Tabs()
		{
			return new GentleList( typeof(rb_Tabs), this, typeof(rb_Portals));
		}

		/// <summary>
		///     
		/// </summary>
		/// 
		/// <returns>
		///     A System.Collections.IList value...
		/// </returns>
		public IList referencedrb_PortalSettings()
		{
			return new GentleList( typeof(rb_PortalSettings), this, typeof(rb_Portals));
		}
		/***PRESERVE_END MANUAL_CODE***/
		#endregion
	}
}
#endregion


