//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rainbow.Framework.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rainbow.Framework.Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        public static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anonymous.
        /// </summary>
        public static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contentpane.
        /// </summary>
        public static string ContentPane {
            get {
                return ResourceManager.GetString("ContentPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string CookiePath {
            get {
                return ResourceManager.GetString("CookiePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVS.
        /// </summary>
        public static string CVS {
            get {
                return ResourceManager.GetString("CVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to footerpane.
        /// </summary>
        public static string FooterPane {
            get {
                return ResourceManager.GetString("FooterPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to headerpane.
        /// </summary>
        public static string HeaderPane {
            get {
                return ResourceManager.GetString("HeaderPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;.
        /// </summary>
        public static string HTML_SPACE {
            get {
                return ResourceManager.GetString("HTML_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leftpane.
        /// </summary>
        public static string LeftPane {
            get {
                return ResourceManager.GetString("LeftPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow_.
        /// </summary>
        public static string PortalPrefix {
            get {
                return ResourceManager.GetString("PortalPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rightpane.
        /// </summary>
        public static string RightPane {
            get {
                return ResourceManager.GetString("RightPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        public static string RoleDelimiter {
            get {
                return ResourceManager.GetString("RoleDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageID.
        /// </summary>
        public static string str_PageID {
            get {
                return ResourceManager.GetString("str_PageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabID.
        /// </summary>
        public static string str_TabID {
            get {
                return ResourceManager.GetString("str_TabID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow_WinMgmt.
        /// </summary>
        public static string UserWinMgmtIndex {
            get {
                return ResourceManager.GetString("UserWinMgmtIndex", resourceCulture);
            }
        }
    }
}
