using System;
using System.Collections;
using System.Data;
using System.Data.SqlClient;
//using Rainbow.BLL.User;
//using Rainbow.BLL.UserConfig;
//using Rainbow.BLL.Utils;
using Rainbow.Configuration;
using Rainbow.Core;
using Rainbow.Data;
using Rainbow.Data.GentleNET;
using Rainbow.Settings;

namespace Rainbow.Security
{
	/// <summary>
	/// The UsersDB class encapsulates all data logic necessary to add/login/query
	/// users within the Portal Users database.
	///
	/// <remarks>
	/// Important Note: The UsersDB class is only used when forms-based cookie
	/// authentication is enabled within the portal.  When windows based
	/// authentication is used instead, then either the Windows SAM or Active Directory
	/// is used to store and validate all username/password credentials.
	/// </remarks>
	/// </summary>
	[History("gman3001", "2004/09/29", "Added the UpdateLastVisit method to update the user's last visit date indicator.")]
	public class UsersDB
	{
		/// <summary>
		///*********************************************************************
		///
		/// AddRole() Method <a name="AddRole"></a>
		///
		/// The AddRole method creates a new security role for the specified portal,
		/// and returns the new RoleID value.
		///
		/// Other relevant sources:
		///     + <a href="AddRole.htm" style="color:green">AddRole Stored Procedure</a>
		///
		///*********************************************************************
		/// </summary>
		/// <param name="portalID" type="int">
		///     <para>
		///         Portal Unique ID
		///     </para>
		/// </param>
		/// <param name="roleName" type="string">
		///     <para>
		///         New Role Name
		///     </para>
		/// </param>
		/// <remarks>
		///			Moved to Roles class.
		/// </remarks>
		/// <returns>
		///     A int value...
		/// </returns>
		[Obsolete("Use Rainow.Data.Roles.Add method.")]
		public int AddRole(int portalID, String roleName)
		{
			using (Roles roles = new Roles())
			{
				return roles.Add(portalID, roleName);
			}

			#region deprecated
			//			if (PortalSettings.UseSingleUserBase) portalID = 0;
			//
			//			// Create Instance of Connection and Command Object
			//			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			//			{
			//				using (SqlCommand myCommand = new SqlCommand("rb_AddRole", myConnection))
			//				{
			//					// Mark the Command as a SPROC
			//					myCommand.CommandType = CommandType.StoredProcedure;
			//					// Add Parameters to SPROC
			//					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int, 4);
			//					parameterPortalID.Value = portalID;
			//					myCommand.Parameters.Add(parameterPortalID);
			//					SqlParameter parameterRoleName = new SqlParameter("@RoleName", SqlDbType.NVarChar, 50);
			//					parameterRoleName.Value = roleName;
			//					myCommand.Parameters.Add(parameterRoleName);
			//					SqlParameter parameterRoleID = new SqlParameter("@RoleID", SqlDbType.Int, 4);
			//					parameterRoleID.Direction = ParameterDirection.Output;
			//					myCommand.Parameters.Add(parameterRoleID);
			//					// Open the database connection and execute the command
			//					myConnection.Open();
			//
			//					try
			//					{
			//						myCommand.ExecuteNonQuery();
			//					}
			//
			//					finally
			//					{
			//						myConnection.Close();
			//					}
			//					// return the role id 
			//					return (int) parameterRoleID.Value;
			//				}
			//			}
			#endregion
		}

		
		/// <summary>
		/// AddUser
		/// Autogenerated by CodeWizard 04/04/2003 17.55.40
		/// </summary>
		/// <param name="portalID"></param>
		/// <param name="name"></param>
		/// <param name="company"></param>
		/// <param name="address"></param>
		/// <param name="city"></param>
		/// <param name="zip"></param>
		/// <param name="countryID"></param>
		/// <param name="stateID"></param>
		/// <param name="pIva"></param>
		/// <param name="cFiscale"></param>
		/// <param name="phone"></param>
		/// <param name="fax"></param>
		/// <param name="password"></param>
		/// <param name="email"></param>
		/// <param name="sendNewsletter"></param>
		/// <returns>The newly created ID</returns>
		[Obsolete("Use Rainbow.Data.Users.Add method.")]
		public int AddUser(int portalID, string name, string company, string address, string city, string zip, string countryID, int stateID, string pIva, string cFiscale, string phone, string fax, string password, string email, Boolean sendNewsletter)
		{
			using (Users users = new Users()) 
			{
				return users.Add(portalID,name,company,address,city,zip,countryID,stateID,pIva,cFiscale,phone,fax,password,email,sendNewsletter);
			}

			#region deprecated
			//			// Create Instance of Connection and Command Object
			//			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			//			{
			//				using (SqlCommand myCommand = new SqlCommand("rb_AddUserFull", myConnection))
			//				{
			//					// Mark the Command as a SPROC
			//					myCommand.CommandType = CommandType.StoredProcedure;
			//					// Add Parameters to SPROC
			//					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
			//					parameterUserID.Direction = ParameterDirection.Output;
			//					myCommand.Parameters.Add(parameterUserID);
			//					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
			//					parameterPortalID.Value = portalID;
			//					myCommand.Parameters.Add(parameterPortalID);
			//					SqlParameter parameterName = new SqlParameter("@Name", SqlDbType.NVarChar, 50);
			//					parameterName.Value = name;
			//					myCommand.Parameters.Add(parameterName);
			//					SqlParameter parameterCompany = new SqlParameter("@Company", SqlDbType.NVarChar, 50);
			//					parameterCompany.Value = company;
			//					myCommand.Parameters.Add(parameterCompany);
			//					SqlParameter parameterAddress = new SqlParameter("@Address", SqlDbType.NVarChar, 50);
			//					parameterAddress.Value = address;
			//					myCommand.Parameters.Add(parameterAddress);
			//					SqlParameter parameterCity = new SqlParameter("@City", SqlDbType.NVarChar, 50);
			//					parameterCity.Value = city;
			//					myCommand.Parameters.Add(parameterCity);
			//					SqlParameter parameterZip = new SqlParameter("@Zip", SqlDbType.NVarChar, 6);
			//					parameterZip.Value = zip;
			//					myCommand.Parameters.Add(parameterZip);
			//					SqlParameter parameterCountryID = new SqlParameter("@CountryID", SqlDbType.NChar, 2);
			//					parameterCountryID.Value = countryID;
			//					myCommand.Parameters.Add(parameterCountryID);
			//					SqlParameter parameterStateID = new SqlParameter("@StateID", SqlDbType.Int);
			//					parameterStateID.Value = stateID;
			//					myCommand.Parameters.Add(parameterStateID);
			//					SqlParameter parameterPIva = new SqlParameter("@PIva", SqlDbType.NVarChar, 11);
			//					parameterPIva.Value = pIva;
			//					myCommand.Parameters.Add(parameterPIva);
			//					SqlParameter parameterCFiscale = new SqlParameter("@CFiscale", SqlDbType.NVarChar, 16);
			//					parameterCFiscale.Value = cFiscale;
			//					myCommand.Parameters.Add(parameterCFiscale);
			//					SqlParameter parameterPhone = new SqlParameter("@Phone", SqlDbType.NVarChar, 50);
			//					parameterPhone.Value = phone;
			//					myCommand.Parameters.Add(parameterPhone);
			//					SqlParameter parameterFax = new SqlParameter("@Fax", SqlDbType.NVarChar, 50);
			//					parameterFax.Value = fax;
			//					myCommand.Parameters.Add(parameterFax);
			//					SqlParameter parameterPassword = new SqlParameter("@Password", SqlDbType.NVarChar, 20);
			//					parameterPassword.Value = password;
			//					myCommand.Parameters.Add(parameterPassword);
			//					SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
			//					parameterEmail.Value = email;
			//					myCommand.Parameters.Add(parameterEmail);
			//					SqlParameter parameterSendNewsletter = new SqlParameter("@SendNewsletter", SqlDbType.Bit);
			//					parameterSendNewsletter.Value = sendNewsletter;
			//					myCommand.Parameters.Add(parameterSendNewsletter);
			//
			//					// Fix by Jeff
			//					// http://www.rainbowportal.net/AspNetForums/ShowPost.aspx?PostID=2331
			//					// Execute the command in a try/catch to catch duplicate username errors 
			//					try
			//					{
			//						// Open the connection and execute the Command 
			//						myConnection.Open();
			//						myCommand.ExecuteNonQuery();
			//					}
			//
			//					catch
			//					{
			//						// failed to create a new user 
			//						throw;
			//					}
			//
			//					finally
			//					{
			//						// Close the Connection 
			//						if (myConnection.State == ConnectionState.Open)
			//							myConnection.Close();
			//					}
			//					// Return the newly created ID
			//					return (int) parameterUserID.Value;
			//				}
			//			}
			#endregion
		}


		/// <summary>
		///*********************************************************************
		///
		/// UsersDB.AddUser() Method <a name="AddUser"></a>
		///
		/// The AddUser method inserts a new user record into the "Users" database table.
		///
		/// Other relevant sources:
		///     + <a href="AddUser.htm" style="color:green">AddUser Stored Procedure</a>
		///
		///*********************************************************************
		/// </summary>
		/// <param name="fullName" type="string">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <param name="email" type="string">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <param name="password" type="string">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <param name="portalID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A int value...
		/// </returns>
		[Obsolete("Use Rainbow.Data.Users.Add method.")]
		public int AddUser(String fullName, String email, String password, int portalID)
		{
			using (Users users = new Users()) 
			{
				return users.Add(fullName,email,password,portalID);
			}

			#region deprecated
			//			// Create Instance of Connection and Command Object
			//			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			//			{
			//				using (SqlCommand myCommand = new SqlCommand("rb_AddUser", myConnection))
			//				{
			//					// Mark the Command as a SPROC
			//					myCommand.CommandType = CommandType.StoredProcedure;
			//					// Add Parameters to SPROC
			//					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
			//					parameterPortalID.Value = portalID;
			//					myCommand.Parameters.Add(parameterPortalID);
			//					SqlParameter parameterFullName = new SqlParameter("@Name", SqlDbType.NVarChar, 50);
			//					parameterFullName.Value = fullName;
			//					myCommand.Parameters.Add(parameterFullName);
			//					SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
			//					parameterEmail.Value = email;
			//					myCommand.Parameters.Add(parameterEmail);
			//					SqlParameter parameterPassword = new SqlParameter("@Password", SqlDbType.NVarChar, 20);
			//					parameterPassword.Value = password;
			//					myCommand.Parameters.Add(parameterPassword);
			//					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
			//					parameterUserID.Direction = ParameterDirection.Output;
			//					myCommand.Parameters.Add(parameterUserID);
			//
			//					// Execute the command in a try/catch to catch duplicate username errors
			//					try
			//					{
			//						// Open the connection and execute the Command
			//						myConnection.Open();
			//						myCommand.ExecuteNonQuery();
			//					}
			//
			//					finally
			//					{
			//						// Close the Connection
			//						if (myConnection.State == ConnectionState.Open)
			//							myConnection.Close();
			//					}
			//					return (int) parameterUserID.Value;
			//				}
			//			}
			#endregion
		}


		/// <summary>
		///*********************************************************************
		///
		/// AddUserRole() Method <a name="AddUserRole"></a>
		///
		/// The AddUserRole method adds the user to the specified security role.
		///
		/// Other relevant sources:
		///     + <a href="AddUserRole.htm" style="color:green">AddUserRole Stored Procedure</a>
		///
		///*********************************************************************
		/// </summary>
		/// <param name="roleID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <param name="userID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A void value...
		/// </returns>
		[Obsolete("Use Rainbow.Data.Roles.AddUserRole method.")]
		public void AddUserRole(int roleID, int userID)
		{
			using (Roles roles = new Roles())
			{
				roles.AddUserRole(roleID, userID);
			}

			#region deprecated
			//			// Create Instance of Connection and Command Object
			//			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			//			{
			//				using (SqlCommand myCommand = new SqlCommand("rb_AddUserRole", myConnection))
			//				{
			//					// Mark the Command as a SPROC
			//					myCommand.CommandType = CommandType.StoredProcedure;
			//					// Add Parameters to SPROC
			//					SqlParameter parameterRoleID = new SqlParameter("@RoleID", SqlDbType.Int, 4);
			//					parameterRoleID.Value = roleID;
			//					myCommand.Parameters.Add(parameterRoleID);
			//					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int, 4);
			//					parameterUserID.Value = userID;
			//					myCommand.Parameters.Add(parameterUserID);
			//					// Open the database connection and execute the command
			//					myConnection.Open();
			//
			//					try
			//					{
			//						myCommand.ExecuteNonQuery();
			//					}
			//
			//					finally
			//					{
			//						myConnection.Close();
			//					}
			//				}
			//			}
			#endregion
		}


		/// <summary>
		///*********************************************************************
		///
		/// DeleteRole() Method <a name="DeleteRole"></a>
		///
		/// The DeleteRole deletes the specified role from the portal database.
		///
		/// Other relevant sources:
		///     + <a href="DeleteRole.htm" style="color:green">DeleteRole Stored Procedure</a>
		///
		///*********************************************************************
		/// </summary>
		/// <param name="roleID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A void value...
		/// </returns>
		public void DeleteRole(int roleID)
		{
			using (Roles r = new Roles())
			{
				r.Remove(roleID);
			}

			#region deprecated
			//			// Create Instance of Connection and Command Object
			//			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			//			{
			//				using (SqlCommand myCommand = new SqlCommand("rb_DeleteRole", myConnection))
			//				{
			//					// Mark the Command as a SPROC
			//					myCommand.CommandType = CommandType.StoredProcedure;
			//					// Add Parameters to SPROC
			//					SqlParameter parameterRoleID = new SqlParameter("@RoleID", SqlDbType.Int, 4);
			//					parameterRoleID.Value = roleID;
			//					myCommand.Parameters.Add(parameterRoleID);
			//					// Open the database connection and execute the command
			//					myConnection.Open();
			//
			//					try
			//					{
			//						myCommand.ExecuteNonQuery();
			//					}
			//
			//					finally
			//					{
			//						myConnection.Close();
			//					}
			//				}
			//			}
			#endregion
		}

		/// <summary>
		/// The DeleteUser method deleted a  user record from the "Users" database table.
		/// </summary>
		/// <param name="userID"></param>
		public void DeleteUser(int userID)
		{
			using (Users u = new Users())
			{
				u.Remove(userID);
			}

			#region deprecated
			//			// Create Instance of Connection and Command Object
			//			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			//			{
			//				using (SqlCommand myCommand = new SqlCommand("rb_DeleteUser", myConnection))
			//				{
			//					// Mark the Command as a SPROC
			//					myCommand.CommandType = CommandType.StoredProcedure;
			//					// Add Parameters to SPROC
			//					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
			//					parameterUserID.Value = userID;
			//					myCommand.Parameters.Add(parameterUserID);
			//					// Open the database connection and execute the command
			//					myConnection.Open();
			//
			//					try
			//					{
			//						myCommand.ExecuteNonQuery();
			//					}
			//
			//					finally
			//					{
			//						myConnection.Close();
			//					}
			//				}
			//			}
			#endregion
		}


		/// <summary>
		///*********************************************************************
		///
		/// DeleteUserRole() Method <a name="DeleteUserRole"></a>
		///
		/// The DeleteUserRole method deletes the user from the specified role.
		///
		/// Other relevant sources:
		///     + <a href="DeleteUserRole.htm" style="color:green">DeleteUserRole Stored Procedure</a>
		///
		///*********************************************************************
		///     
		/// </summary>
		/// <param name="roleID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <param name="userID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A void value...
		/// </returns>
		public void DeleteUserRole(int roleID, int userID)
		{
			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_DeleteUserRole", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Add Parameters to SPROC
					SqlParameter parameterRoleID = new SqlParameter("@RoleID", SqlDbType.Int, 4);
					parameterRoleID.Value = roleID;
					myCommand.Parameters.Add(parameterRoleID);
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int, 4);
					parameterUserID.Value = userID;
					myCommand.Parameters.Add(parameterUserID);
					// Open the database connection and execute the command
					myConnection.Open();

					try
					{
						myCommand.ExecuteNonQuery();
					}

					finally
					{
						myConnection.Close();
					}
				}
			}
		}

		/// <summary>
		/// Get a full user for store on authentication cookie
		/// </summary>
		/// <param name="email"></param>
		/// <param name="portalID"></param>
		/// <returns></returns>
		public User GetCurrentUser(String email, int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;
			SqlDataReader dr = GetSingleUser(email, portalID);
			string name = "unknown";
			string userID = "0";

			// Read first row from database
			try
			{
				if (dr.Read())
				{
					userID = dr["userID"].ToString();
					name = dr["Name"].ToString();
					email = dr["Email"].ToString();
				}

				else
					throw new ApplicationException("User not found");
			}

			finally
			{
				//by Manu fix close bug #2 found
				//Included in finally to be sure is always closed
				dr.Close(); //by Manu, fixed bug 807858
			}
			return new User(name, email, userID);
		}

		/// <summary>
		/// Get Current UserID
		/// </summary>
		/// <param name="UserEmail"></param>
		/// <param name="portalID"></param>
		/// <returns></returns>
		public int GetCurrentUserID(string userEmail, int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;
			int userID = 0;

			using (SqlDataReader drUsers = GetSingleUser(userEmail, portalID))
			{
				try
				{
					if (drUsers.Read())
						userID = Int32.Parse(drUsers["UserID"].ToString());
				}

				finally
				{
					drUsers.Close(); //by Manu, fixed bug 807858
				}
			}
			return userID;
		}

		/// <summary>
		///
		/// ROLES
		///
		///*********************************************************************
		///
		/// GetPortalRoles() Method <a name="GetPortalRoles"></a>
		///
		/// The GetPortalRoles method returns a list of all role names for the 
		/// specified portal.
		///
		/// Other relevant sources:
		///     + <a href="GetRolesByUser.htm" style="color:green">GetPortalRoles Stored Procedure</a>
		///
		///*********************************************************************
		/// </summary>
		/// <param name="portalID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A System.Data.SqlClient.SqlDataReader value...
		/// </returns>
		[Obsolete("Replace me")]
		public SqlDataReader GetPortalRoles(int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;
			// Create Instance of Connection and Command Object
			SqlConnection myConnection = PortalSettings.SqlConnectionString;
			SqlCommand myCommand = new SqlCommand("rb_GetPortalRoles", myConnection);
			// Mark the Command as a SPROC
			myCommand.CommandType = CommandType.StoredProcedure;
			// Add Parameters to SPROC
			SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int, 4);
			parameterPortalID.Value = portalID;
			myCommand.Parameters.Add(parameterPortalID);
			// Open the database connection and execute the command
			myConnection.Open();
			SqlDataReader dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
			// Return the datareader
			return dr;
		}

		/// <summary>
		///
		/// USER ROLES
		///
		///*********************************************************************
		///
		/// GetRoleMembers() Method <a name="GetRoleMembers"></a>
		///
		/// The GetRoleMembers method returns a list of all members in the specified
		/// security role.
		///
		/// Other relevant sources:
		///     + <a href="GetRoleMembers.htm" style="color:green">GetRoleMembers Stored Procedure</a>
		///
		///*********************************************************************
		/// </summary>
		/// <param name="roleID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A System.Data.SqlClient.SqlDataReader value...
		/// </returns>
		[Obsolete("Replace me")]
		public SqlDataReader GetRoleMembers(int roleID)
		{
			// Create Instance of Connection and Command Object
			SqlConnection myConnection = PortalSettings.SqlConnectionString;
			SqlCommand myCommand = new SqlCommand("rb_GetRoleMembership", myConnection);
			// Mark the Command as a SPROC
			myCommand.CommandType = CommandType.StoredProcedure;
			SqlParameter parameterRoleID = new SqlParameter("@RoleID", SqlDbType.Int, 4);
			parameterRoleID.Value = roleID;
			myCommand.Parameters.Add(parameterRoleID);
			// Open the database connection and execute the command
			myConnection.Open();
			SqlDataReader dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
			// Return the datareader
			return dr;
		}

		/// <summary>
		/// Added by John Mandia (www.whitelightsolutions.com) 15/08/04
		/// This Method Is Used To Retrieve All Users Who Do Not Belong To A Particular Role
		/// </summary>
		/// <param name="roleID"></param>
		/// <param name="portalID"></param>
		/// <returns>A SqlDataReader</returns>
		[Obsolete("Replace me")]
		public SqlDataReader GetRoleNonMembers(int roleID, int portalID)
		{
			// Create Instance of Connection and Command Object
			SqlConnection myConnection = PortalSettings.SqlConnectionString;
			SqlCommand myCommand = new SqlCommand("rb_GetRoleNonMembership", myConnection);
			// Mark the Command as a SPROC
			myCommand.CommandType = CommandType.StoredProcedure;
			SqlParameter parameterRoleID = new SqlParameter("@RoleID", SqlDbType.Int, 4);
			parameterRoleID.Value = roleID;
			myCommand.Parameters.Add(parameterRoleID);
			SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int, 4);

			if (PortalSettings.UseSingleUserBase)
				parameterPortalID.Value = 0;

			else
				parameterPortalID.Value = portalID;
			myCommand.Parameters.Add(parameterPortalID);
			// Open the database connection and execute the command
			myConnection.Open();
			SqlDataReader dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
			// Return the datareader
			return dr;
		}

		/// <summary>
		/// Added by John Mandia (www.whitelightsolutions.com) 01/09/04 (Note did not add a stored procedure to sql for this method as it's uses are limited and we already have a lot of stored procedures in the rainbow database)
		/// This Method Is Used To Retrieve All Users Who Do Not Belong To A Particular Role But 
		/// Belong To A Second Role.
		/// </summary>
		/// <param name="roleID"></param>
		/// <param name="portalID"></param>
		/// <param name="filterRoleID"></param>
		/// <returns>A SqlDataReader</returns>
		[Obsolete("Replace me")]
		public SqlDataReader GetRoleNonMembersFiltered(int roleID, int portalID, int filterRoleID)
		{
			// Create Instance of Connection and Command Object
			SqlConnection myConnection = PortalSettings.SqlConnectionString;
			// Set up a command with the given query and associate
			// this with the current connection.
			string commandText = "SELECT rb_UserRoles.UserID, Name, Email FROM rb_UserRoles INNER JOIN rb_Users On rb_Users.UserID = rb_UserRoles.UserID WHERE rb_UserRoles.RoleID = @RoleIDFilter AND PortalID = @PortalID AND rb_Users.UserID  NOT IN (SELECT UserID FROM rb_UserRoles WHERE rb_UserRoles.RoleID = @RoleID)";
			SqlCommand myCommand = new SqlCommand(commandText, myConnection);
			SqlParameter parameterRoleID = new SqlParameter("@RoleID", SqlDbType.Int, 4);
			parameterRoleID.Value = roleID;
			myCommand.Parameters.Add(parameterRoleID);
			SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int, 4);

			if (PortalSettings.UseSingleUserBase)
				parameterPortalID.Value = 0;

			else
				parameterPortalID.Value = portalID;
			myCommand.Parameters.Add(parameterPortalID);
			SqlParameter parameterFilterRoleID = new SqlParameter("@RoleIDFilter", SqlDbType.Int, 4);
			parameterFilterRoleID.Value = filterRoleID;
			myCommand.Parameters.Add(parameterFilterRoleID);
			// Open the database connection and execute the command
			myConnection.Open();
			SqlDataReader dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
			// Return the datareader
			return dr;
		}

		/// <summary>
		///*********************************************************************
		///
		/// GetRoles() Method <a name="GetRoles"></a>
		///
		/// The GetRoles method returns a list of role names for the user.
		///
		/// Other relevant sources:
		///     + <a href="GetRolesByUser.htm" style="color:green">GetRolesByUser Stored Procedure</a>
		///
		///*********************************************************************
		/// </summary>
		/// <param name="email" type="string">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <param name="portalID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A string[] value...
		/// </returns>
		public String[] GetRoles(String email, int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;

			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_GetRolesByUser", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Add Parameters to SPROC
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);
					SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
					parameterEmail.Value = email;
					myCommand.Parameters.Add(parameterEmail);
					// Open the database connection and execute the command
					SqlDataReader dr;
					myConnection.Open();
					dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
					// create a String array from the data
					ArrayList userRoles = new ArrayList();

					try
					{
						while (dr.Read())
							userRoles.Add(dr["RoleName"]);
					}

					finally
					{
						dr.Close();
					}
					// Return the String array of roles
					return (String[]) userRoles.ToArray(typeof (String));
				}
			}
		}

		/// <summary>
		///*********************************************************************
		///
		/// UsersDB.GetRolesByUser() Method <a name="GetRolesByUser"></a>
		///
		/// The DeleteUser method deleted a  user record from the "Users" database table.
		///
		/// Other relevant sources:
		///     + <a href="GetRolesByUser.htm" style="color:green">GetRolesByUser Stored Procedure</a>
		///
		///*********************************************************************
		/// </summary>
		/// <param name="email" type="string">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <param name="portalID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A System.Data.SqlClient.SqlDataReader value...
		/// </returns>
		[Obsolete("Replace me")]
		public SqlDataReader GetRolesByUser(String email, int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;
			// Create Instance of Connection and Command Object
			SqlConnection myConnection = PortalSettings.SqlConnectionString;
			SqlCommand myCommand = new SqlCommand("rb_GetRolesByUser", myConnection);
			// Mark the Command as a SPROC
			myCommand.CommandType = CommandType.StoredProcedure;
			// Add Parameters to SPROC
			SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
			parameterPortalID.Value = portalID;
			myCommand.Parameters.Add(parameterPortalID);
			SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
			parameterEmail.Value = email;
			myCommand.Parameters.Add(parameterEmail);
			// Open the database connection and execute the command
			myConnection.Open();
			SqlDataReader dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
			// Return the datareader
			return dr;
		}

		/// <summary>
		/// GetSingleUser Method
		///
		/// The GetSingleUser method returns a SqlDataReader containing details
		/// about a specific user from the Users database table.
		/// </summary>
		/// <param name="email"></param>
		/// <param name="portalID"></param>
		/// <param name="IDLang"></param>
		/// <returns></returns>
		[Obsolete("Replace me")]
		public SqlDataReader GetSingleUser(String email, int portalID, string iDLang)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;
			// Create Instance of Connection and Command Object
			SqlConnection myConnection = PortalSettings.SqlConnectionString;
			SqlCommand myCommand = new SqlCommand("rb_GetSingleUser", myConnection);
			// Mark the Command as a SPROC
			myCommand.CommandType = CommandType.StoredProcedure;
			// Add Parameters to SPROC
			SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
			parameterPortalID.Value = portalID;
			myCommand.Parameters.Add(parameterPortalID);
			SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
			parameterEmail.Value = email;
			myCommand.Parameters.Add(parameterEmail);
			SqlParameter parameterIDLang = new SqlParameter("@IDLang", SqlDbType.NChar, 2);
			parameterIDLang.Value = iDLang;
			myCommand.Parameters.Add(parameterIDLang);
			// Open the database connection and execute the command
			myConnection.Open();
			SqlDataReader dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
			// Return the datareader
			return dr;
		}

		/// <summary>
		/// GetSingleUser Method
		///
		/// The GetSingleUser method returns a SqlDataReader containing details
		/// about a specific user from the Users database table.
		/// </summary>
		/// <param name="email"></param>
		/// <param name="portalID"></param>
		/// <returns></returns>
		[Obsolete("Replace me")]
		public SqlDataReader GetSingleUser(String email, int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;
			// Create Instance of Connection and Command Object
			SqlConnection myConnection = PortalSettings.SqlConnectionString;
			SqlCommand myCommand = new SqlCommand("rb_GetSingleUser", myConnection);
			// Mark the Command as a SPROC
			myCommand.CommandType = CommandType.StoredProcedure;
			// Add Parameters to SPROC
			SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
			parameterPortalID.Value = portalID;
			myCommand.Parameters.Add(parameterPortalID);
			SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
			parameterEmail.Value = email;
			myCommand.Parameters.Add(parameterEmail);
			// Open the database connection and execute the command
			myConnection.Open();
			SqlDataReader dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
			// Return the datareader
			return dr;
		}

		/// <summary>
		///*********************************************************************
		///
		/// UsersDB.GetUncheckedUsers() Method <a name="GetUsers"></a>
		///
		/// Get only the records with CheckMail disabled from the "Users" database table.
		/// To avoid troubles MailCheck cannot check more than 10 users at time
		///
		/// Other relevant sources:
		///     + <a href="GetUncheckedUsers.htm" style="color:green">GetUncheckedUsers Stored Procedure</a>
		///
		///*********************************************************************
		/// </summary>
		/// <param name="portalID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A System.Data.SqlClient.SqlDataReader value...
		/// </returns>
		[Obsolete("Replace me")]
		public SqlDataReader GetUncheckedUsers(int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;
			// Create Instance of Connection and Command Object
			SqlConnection myConnection = PortalSettings.SqlConnectionString;
			SqlCommand myCommand = new SqlCommand("rb_GetUncheckedUsers", myConnection);
			// Mark the Command as a SPROC
			myCommand.CommandType = CommandType.StoredProcedure;
			// Add Parameters to SPROC
			SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
			parameterPortalID.Value = portalID;
			myCommand.Parameters.Add(parameterPortalID);
			// Open the database connection and execute the command
			myConnection.Open();
			SqlDataReader dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
			// Return the datareader
			return dr;
		}

		/// <summary>
		///  UsersDB.GetUsers() Method <a name="GetUsers"></a>
		///  Get record from the "Users" database table.
		/// </summary>
		/// <param name="portalID"></param>
		/// <returns></returns>
		[Obsolete("FIX ME:Should return a collection of business layer types UserItem, not a dataset.")]
		public DataSet GetUsers(int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;

			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlDataAdapter myCommand = new SqlDataAdapter("rb_GetUsers", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.SelectCommand.CommandType = CommandType.StoredProcedure;
					// Add Parameters to SPROC
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.SelectCommand.Parameters.Add(parameterPortalID);

					// Create and Fill the DataSet
					using (DataSet myDataSet = new DataSet())
					{
						myCommand.Fill(myDataSet);
						myCommand.Dispose(); //by Manu fix close bug #2
						myConnection.Close(); //by Manu fix close bug #2
						myConnection.Dispose(); //by Manu fix close bug #2
						// Return the dataset
						return myDataSet;
					}
				}
			}
		}

		/// <summary>
		/// The GetUsersCount method returns the users count.
		/// Uses GetUsersCount Stored Procedure.
		/// </summary>
		/// <param name="portalID"></param>
		/// <returns></returns>
		public int GetUsersCount(int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;

			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_GetUsersCount", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Add Parameters to SPROC
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int, 4);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);
					SqlParameter parameterUsersCount = new SqlParameter("@UsersCount", SqlDbType.Int, 4);
					parameterUsersCount.Direction = ParameterDirection.Output;
					myCommand.Parameters.Add(parameterUsersCount);
					// Open the database connection and execute the command
					myConnection.Open();

					try
					{
						myCommand.ExecuteNonQuery();
					}

					finally
					{
						myConnection.Close();
					}
					// Return the datareader
					return Convert.ToInt32(parameterUsersCount.Value);
				}
			}
		}

		/// <summary>
		///*********************************************************************
		///
		/// UsersDB.GetUsersNoPassword() Method <a name="GetUsers"></a>
		///
		/// Get only the records with SendNewsletter enabled from the "Users" database table.
		///
		/// Other relevant sources:
		///     + <a href="GetUsersNoPassword.htm" style="color:green">GetUsersNoPassword Stored Procedure</a>
		///
		///*********************************************************************
		/// </summary>
		/// <param name="portalID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A System.Data.SqlClient.SqlDataReader value...
		/// </returns>
		[Obsolete("Replace me")]
		public SqlDataReader GetUsersNoPassword(int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;
			// Create Instance of Connection and Command Object
			SqlConnection myConnection = PortalSettings.SqlConnectionString;
			SqlCommand myCommand = new SqlCommand("rb_GetUsersNoPassword", myConnection);
			// Mark the Command as a SPROC
			myCommand.CommandType = CommandType.StoredProcedure;
			// Add Parameters to SPROC
			SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
			parameterPortalID.Value = portalID;
			myCommand.Parameters.Add(parameterPortalID);
			// Open the database connection and execute the command
			myConnection.Open();
			SqlDataReader dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
			// Return the datareader
			return dr;
		}

		/// <summary>
		/// Added by John Mandia (www.whitelightsolutions.com) 15/08/2004
		/// This Method Is Used To Retrieve All Users Who Do Not Belong To A Role
		/// </summary>
		/// <returns>A SqlDataReader</returns>
		[Obsolete("Replace me")]
		public SqlDataReader GetUsersNoRole(int portalID)
		{
			// Create Instance of Connection and Command Object
			SqlConnection myConnection = PortalSettings.SqlConnectionString;
			SqlCommand myCommand = new SqlCommand("rb_GetUsersNoRole", myConnection);
			// Mark the Command as a SPROC
			myCommand.CommandType = CommandType.StoredProcedure;
			SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int, 4);

			if (PortalSettings.UseSingleUserBase)
				parameterPortalID.Value = 0;

			else
				parameterPortalID.Value = portalID;
			myCommand.Parameters.Add(parameterPortalID);
			// Open the database connection and execute the command
			myConnection.Open();
			SqlDataReader dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
			// Return the datareader
			return dr;
		}

		/// <summary>
		///     
		/// </summary>
		/// <param name="portalID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A System.Data.SqlClient.SqlDataReader value...
		/// </returns>
		[Obsolete("Replace me")]
		public SqlDataReader GetUsersReader(int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;
			// Create Instance of Connection and Command Object
			SqlConnection myConnection = PortalSettings.SqlConnectionString;
			SqlCommand myCommand = new SqlCommand("rb_GetUsers", myConnection);
			// Mark the Command as a SPROC
			myCommand.CommandType = CommandType.StoredProcedure;
			// Add Parameters to SPROC
			SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
			parameterPortalID.Value = portalID;
			myCommand.Parameters.Add(parameterPortalID);
			// Open the database connection and execute the command
			myConnection.Open();
			SqlDataReader dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
			// Return the datareader
			return dr;
		}

		/// <summary>
		/// UsersDB.Login() Method.
		/// The Login method validates a id/password pair against credentials
		/// stored in the users database.  If the id/password pair is valid,
		/// the method returns user's name.
		/// </summary>
		/// <remarks>UserLogin Stored Procedure</remarks>
		/// <param name="uid"></param>
		/// <param name="password"></param>
		/// <param name="portalID"></param>
		/// <returns></returns>
		public User Login(int uid, String password, int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;

			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_UserLoginByID", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Add Parameters to SPROC
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
					parameterUserID.Value = uid;
					myCommand.Parameters.Add(parameterUserID);
					/* The following block of code was replaced with the preceeding
					 * block of code to resolve issue #840691
					 * parameterEmail variable should be named parameterUserId
					 * Author: Cemil Ayvaz
					 * Email : cemil_ayvaz@yahoo.com
					 * Date  : 2004-05-24
					 * 
					SqlParameter parameterEmail = new SqlParameter("@UserID", SqlDbType.Int);
					parameterEmail.Value = uid;
					myCommand.Parameters.Add(parameterEmail);
					*/
					SqlParameter parameterPassword = new SqlParameter("@Password", SqlDbType.NVarChar, 20);
					parameterPassword.Value = password;
					myCommand.Parameters.Add(parameterPassword);
					// Open the database connection and execute the command
					SqlDataReader dr;
					myConnection.Open();
					dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
					User myUser = null;

					try
					{
						if (dr.Read())
							myUser = new User(dr["Name"].ToString(), dr["Email"].ToString(), dr["UserID"].ToString());
					}

					finally
					{
						dr.Close(); //by Manu, fixed bug 807858
					}
					return myUser;
				}
			}
		}

		/// <summary>
		/// UsersDB.Login() Method.
		/// The Login method validates a email/password pair against credentials
		/// stored in the users database.  If the email/password pair is valid,
		/// the method returns user's name.
		/// </summary>
		/// <remarks>UserLogin Stored Procedure</remarks>
		/// <param name="email"></param>
		/// <param name="password"></param>
		/// <param name="portalID"></param>
		/// <returns></returns>
		public User Login(String email, String password, int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;

			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_UserLogin", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Add Parameters to SPROC
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);
					SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
					parameterEmail.Value = email;
					myCommand.Parameters.Add(parameterEmail);
					SqlParameter parameterPassword = new SqlParameter("@Password", SqlDbType.NVarChar, 20);
					parameterPassword.Value = password;
					myCommand.Parameters.Add(parameterPassword);
					// Open the database connection and execute the command
					SqlDataReader dr;
					myConnection.Open();
					dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);
					User myUser = null;

					try
					{
						if (dr.Read())
							myUser = new User(dr["Name"].ToString(), dr["Email"].ToString(), dr["UserID"].ToString());
					}

					finally
					{
						dr.Close(); //by Manu, fixed bug 807858
					}
					return myUser;
				}
			}
		}

		// Added by gman3001 9/29/2004
		/// <summary>
		/// UpdateLastVisit Method
		///
		/// The UpdateLastVisit method updates the specified user's last visit date in the Users database table.
		/// </summary>
		/// <param name="email"></param>
		/// <param name="portalID"></param>
		/// <returns></returns>
		public void UpdateLastVisit(string email, int portalID)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;

			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_UpdateLastVisit", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Add Parameters to SPROC
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);
					SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
					parameterEmail.Value = email;
					myCommand.Parameters.Add(parameterEmail);
					// Open the database connection and execute the command
					myConnection.Open();
					myCommand.ExecuteNonQuery();
					myConnection.Close();
				}
			}
		}

		/// <summary>
		///*********************************************************************
		///
		/// UpdateRole() Method <a name="UpdateRole"></a>
		///
		/// The UpdateRole method updates the friendly name of the specified role.
		///
		/// Other relevant sources:
		///     + <a href="UpdateRole.htm" style="color:green">UpdateRole Stored Procedure</a>
		///
		///*********************************************************************
		/// </summary>
		/// <param name="roleID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <param name="roleName" type="string">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A void value...
		/// </returns>
		public void UpdateRole(int roleID, String roleName)
		{
			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_UpdateRole", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Add Parameters to SPROC
					SqlParameter parameterRoleID = new SqlParameter("@RoleID", SqlDbType.Int, 4);
					parameterRoleID.Value = roleID;
					myCommand.Parameters.Add(parameterRoleID);
					SqlParameter parameterRoleName = new SqlParameter("@RoleName", SqlDbType.NVarChar, 50);
					parameterRoleName.Value = roleName;
					myCommand.Parameters.Add(parameterRoleName);
					// Open the database connection and execute the command
					myConnection.Open();

					try
					{
						myCommand.ExecuteNonQuery();
					}

					finally
					{
						myConnection.Close();
					}
				}
			}
		}

		/// <summary>
		/// UpdateUser
		/// This overload allow to change identity of the user
		/// </summary>
		/// <param name="oldUserID"></param>
		/// <param name="userID"></param>
		/// <param name="portalID"></param>
		/// <param name="name"></param>
		/// <param name="company"></param>
		/// <param name="address"></param>
		/// <param name="city"></param>
		/// <param name="zip"></param>
		/// <param name="countryID"></param>
		/// <param name="stateID"></param>
		/// <param name="pIva"></param>
		/// <param name="cFiscale"></param>
		/// <param name="phone"></param>
		/// <param name="fax"></param>
		/// <param name="password"></param>
		/// <param name="email"></param>
		/// <param name="sendNewsletter"></param>
		public void UpdateUser(int oldUserID, int userID, int portalID, string name, string company, string address, string city, string zip, string countryID, int stateID, string pIva, string cFiscale, string phone, string fax, string password, string email, Boolean sendNewsletter)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;

			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_UpdateUserFull", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Update Parameters to SPROC
					SqlParameter parameteroldUserID = new SqlParameter("@OldUserID", SqlDbType.Int);
					parameteroldUserID.Value = oldUserID;
					myCommand.Parameters.Add(parameteroldUserID);
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
					parameterUserID.Value = userID;
					myCommand.Parameters.Add(parameterUserID);
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);
					SqlParameter parameterName = new SqlParameter("@Name", SqlDbType.NVarChar, 50);
					parameterName.Value = name;
					myCommand.Parameters.Add(parameterName);
					SqlParameter parameterCompany = new SqlParameter("@Company", SqlDbType.NVarChar, 50);
					parameterCompany.Value = company;
					myCommand.Parameters.Add(parameterCompany);
					SqlParameter parameterAddress = new SqlParameter("@Address", SqlDbType.NVarChar, 50);
					parameterAddress.Value = address;
					myCommand.Parameters.Add(parameterAddress);
					SqlParameter parameterCity = new SqlParameter("@City", SqlDbType.NVarChar, 50);
					parameterCity.Value = city;
					myCommand.Parameters.Add(parameterCity);
					SqlParameter parameterZip = new SqlParameter("@Zip", SqlDbType.NVarChar, 6);
					parameterZip.Value = zip;
					myCommand.Parameters.Add(parameterZip);
					SqlParameter parameterCountryID = new SqlParameter("@CountryID", SqlDbType.NChar, 2);
					parameterCountryID.Value = countryID;
					myCommand.Parameters.Add(parameterCountryID);
					SqlParameter parameterStateID = new SqlParameter("@StateID", SqlDbType.Int);
					parameterStateID.Value = stateID;
					myCommand.Parameters.Add(parameterStateID);
					SqlParameter parameterPIva = new SqlParameter("@PIva", SqlDbType.NVarChar, 11);
					parameterPIva.Value = pIva;
					myCommand.Parameters.Add(parameterPIva);
					SqlParameter parameterCFiscale = new SqlParameter("@CFiscale", SqlDbType.NVarChar, 16);
					parameterCFiscale.Value = cFiscale;
					myCommand.Parameters.Add(parameterCFiscale);
					SqlParameter parameterPhone = new SqlParameter("@Phone", SqlDbType.NVarChar, 50);
					parameterPhone.Value = phone;
					myCommand.Parameters.Add(parameterPhone);
					SqlParameter parameterFax = new SqlParameter("@Fax", SqlDbType.NVarChar, 50);
					parameterFax.Value = fax;
					myCommand.Parameters.Add(parameterFax);
					SqlParameter parameterPassword = new SqlParameter("@Password", SqlDbType.NVarChar, 20);
					parameterPassword.Value = password;
					myCommand.Parameters.Add(parameterPassword);
					SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
					parameterEmail.Value = email;
					myCommand.Parameters.Add(parameterEmail);
					SqlParameter parameterSendNewsletter = new SqlParameter("@SendNewsletter", SqlDbType.Bit);
					parameterSendNewsletter.Value = sendNewsletter;
					myCommand.Parameters.Add(parameterSendNewsletter);

					// Execute the command in a try/catch to catch duplicate username errors
					try
					{
						// Open the connection and execute the Command
						myConnection.Open();
						myCommand.ExecuteNonQuery();
					}

					catch
					{
						throw;
					}

					finally
					{
						// Close the Connection
						if (myConnection.State == ConnectionState.Open)
							myConnection.Close();
					}
				}
			}
		}

		/// <summary>
		/// UpdateUser
		/// This overload allow to change identity of the user
		/// </summary>
		/// <param name="oldUserID"></param>
		/// <param name="userID"></param>
		/// <param name="portalID"></param>
		/// <param name="name"></param>
		/// <param name="password"></param>
		/// <param name="email"></param>
		public void UpdateUser(int oldUserID, int userID, int portalID, string name, string password, string email)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;

			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_UpdateUserFull", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Update Parameters to SPROC
					SqlParameter parameteroldUserID = new SqlParameter("@OldUserID", SqlDbType.Int);
					parameteroldUserID.Value = oldUserID;
					myCommand.Parameters.Add(parameteroldUserID);
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
					parameterUserID.Value = userID;
					myCommand.Parameters.Add(parameterUserID);
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);
					SqlParameter parameterName = new SqlParameter("@Name", SqlDbType.NVarChar, 50);
					parameterName.Value = name;
					myCommand.Parameters.Add(parameterName);
					SqlParameter parameterPassword = new SqlParameter("@Password", SqlDbType.NVarChar, 20);
					parameterPassword.Value = password;
					myCommand.Parameters.Add(parameterPassword);
					SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
					parameterEmail.Value = email;
					myCommand.Parameters.Add(parameterEmail);

					// Execute the command in a try/catch to catch duplicate username errors
					try
					{
						// Open the connection and execute the Command
						myConnection.Open();
						myCommand.ExecuteNonQuery();
					}

					catch
					{
						throw;
					}

					finally
					{
						// Close the Connection
						if (myConnection.State == ConnectionState.Open)
							myConnection.Close();
					}
				}
			}
		}

		/// <summary>
		/// method added by Thierry (tiptopweb) on 5 May 2003
		/// The UpdateUser method inserts a new user record into the "Users" database table.
		/// </summary>
		/// <param name="userID"></param>
		/// <param name="portalID"></param>
		/// <param name="name"></param>
		/// <param name="company"></param>
		/// <param name="address"></param>
		/// <param name="city"></param>
		/// <param name="zip"></param>
		/// <param name="countryID"></param>
		/// <param name="stateID"></param>
		/// <param name="pIva"></param>
		/// <param name="cFiscale"></param>
		/// <param name="phone"></param>
		/// <param name="fax"></param>
		/// <param name="email"></param>
		/// <param name="sendNewsletter"></param>
		public void UpdateUser(int userID, int portalID, string name, string company, string address, string city, string zip, string countryID, int stateID, string pIva, string cFiscale, string phone, string fax, string email, Boolean sendNewsletter)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;

			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_UpdateUserFullNoPassword", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Update Parameters to SPROC
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
					parameterUserID.Value = userID;
					myCommand.Parameters.Add(parameterUserID);
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);
					SqlParameter parameterName = new SqlParameter("@Name", SqlDbType.NVarChar, 50);
					parameterName.Value = name;
					myCommand.Parameters.Add(parameterName);
					SqlParameter parameterCompany = new SqlParameter("@Company", SqlDbType.NVarChar, 50);
					parameterCompany.Value = company;
					myCommand.Parameters.Add(parameterCompany);
					SqlParameter parameterAddress = new SqlParameter("@Address", SqlDbType.NVarChar, 50);
					parameterAddress.Value = address;
					myCommand.Parameters.Add(parameterAddress);
					SqlParameter parameterCity = new SqlParameter("@City", SqlDbType.NVarChar, 50);
					parameterCity.Value = city;
					myCommand.Parameters.Add(parameterCity);
					SqlParameter parameterZip = new SqlParameter("@Zip", SqlDbType.NVarChar, 6);
					parameterZip.Value = zip;
					myCommand.Parameters.Add(parameterZip);
					SqlParameter parameterCountryID = new SqlParameter("@CountryID", SqlDbType.NChar, 2);
					parameterCountryID.Value = countryID;
					myCommand.Parameters.Add(parameterCountryID);
					SqlParameter parameterStateID = new SqlParameter("@StateID", SqlDbType.Int);
					parameterStateID.Value = stateID;
					myCommand.Parameters.Add(parameterStateID);
					SqlParameter parameterPIva = new SqlParameter("@PIva", SqlDbType.NVarChar, 11);
					parameterPIva.Value = pIva;
					myCommand.Parameters.Add(parameterPIva);
					SqlParameter parameterCFiscale = new SqlParameter("@CFiscale", SqlDbType.NVarChar, 16);
					parameterCFiscale.Value = cFiscale;
					myCommand.Parameters.Add(parameterCFiscale);
					SqlParameter parameterPhone = new SqlParameter("@Phone", SqlDbType.NVarChar, 50);
					parameterPhone.Value = phone;
					myCommand.Parameters.Add(parameterPhone);
					SqlParameter parameterFax = new SqlParameter("@Fax", SqlDbType.NVarChar, 50);
					parameterFax.Value = fax;
					myCommand.Parameters.Add(parameterFax);
					//			SqlParameter parameterPassword = new SqlParameter("@Password", SqlDbType.NVarChar, 20);
					//			parameterPassword.Value = password;
					//			myCommand.Parameters.Add(parameterPassword);
					//
					SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
					parameterEmail.Value = email;
					myCommand.Parameters.Add(parameterEmail);
					SqlParameter parameterSendNewsletter = new SqlParameter("@SendNewsletter", SqlDbType.Bit);
					parameterSendNewsletter.Value = sendNewsletter;
					myCommand.Parameters.Add(parameterSendNewsletter);
					// Execute the command
					myConnection.Open();

					try
					{
						myCommand.ExecuteNonQuery();
					}

					finally
					{
						myConnection.Close();
					}
				}
			}
		}

		/// <summary>
		/// UpdateUser
		/// Autogenerated by CodeWizard 04/04/2003 17.55.40
		/// </summary>
		/// <param name="userID"></param>
		/// <param name="portalID"></param>
		/// <param name="name"></param>
		/// <param name="company"></param>
		/// <param name="address"></param>
		/// <param name="city"></param>
		/// <param name="zip"></param>
		/// <param name="countryID"></param>
		/// <param name="stateID"></param>
		/// <param name="pIva"></param>
		/// <param name="cFiscale"></param>
		/// <param name="phone"></param>
		/// <param name="fax"></param>
		/// <param name="password"></param>
		/// <param name="email"></param>
		/// <param name="sendNewsletter"></param>
		public void UpdateUser(int userID, int portalID, string name, string company, string address, string city, string zip, string countryID, int stateID, string pIva, string cFiscale, string phone, string fax, string password, string email, Boolean sendNewsletter)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;

			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_UpdateUserFull", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Update Parameters to SPROC
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
					parameterUserID.Value = userID;
					myCommand.Parameters.Add(parameterUserID);
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);
					SqlParameter parameterName = new SqlParameter("@Name", SqlDbType.NVarChar, 50);
					parameterName.Value = name;
					myCommand.Parameters.Add(parameterName);
					SqlParameter parameterCompany = new SqlParameter("@Company", SqlDbType.NVarChar, 50);
					parameterCompany.Value = company;
					myCommand.Parameters.Add(parameterCompany);
					SqlParameter parameterAddress = new SqlParameter("@Address", SqlDbType.NVarChar, 50);
					parameterAddress.Value = address;
					myCommand.Parameters.Add(parameterAddress);
					SqlParameter parameterCity = new SqlParameter("@City", SqlDbType.NVarChar, 50);
					parameterCity.Value = city;
					myCommand.Parameters.Add(parameterCity);
					SqlParameter parameterZip = new SqlParameter("@Zip", SqlDbType.NVarChar, 6);
					parameterZip.Value = zip;
					myCommand.Parameters.Add(parameterZip);
					SqlParameter parameterCountryID = new SqlParameter("@CountryID", SqlDbType.NChar, 2);
					parameterCountryID.Value = countryID;
					myCommand.Parameters.Add(parameterCountryID);
					SqlParameter parameterStateID = new SqlParameter("@StateID", SqlDbType.Int);
					parameterStateID.Value = stateID;
					myCommand.Parameters.Add(parameterStateID);
					SqlParameter parameterPIva = new SqlParameter("@PIva", SqlDbType.NVarChar, 11);
					parameterPIva.Value = pIva;
					myCommand.Parameters.Add(parameterPIva);
					SqlParameter parameterCFiscale = new SqlParameter("@CFiscale", SqlDbType.NVarChar, 16);
					parameterCFiscale.Value = cFiscale;
					myCommand.Parameters.Add(parameterCFiscale);
					SqlParameter parameterPhone = new SqlParameter("@Phone", SqlDbType.NVarChar, 50);
					parameterPhone.Value = phone;
					myCommand.Parameters.Add(parameterPhone);
					SqlParameter parameterFax = new SqlParameter("@Fax", SqlDbType.NVarChar, 50);
					parameterFax.Value = fax;
					myCommand.Parameters.Add(parameterFax);
					SqlParameter parameterPassword = new SqlParameter("@Password", SqlDbType.NVarChar, 20);
					parameterPassword.Value = password;
					myCommand.Parameters.Add(parameterPassword);
					SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
					parameterEmail.Value = email;
					myCommand.Parameters.Add(parameterEmail);
					SqlParameter parameterSendNewsletter = new SqlParameter("@SendNewsletter", SqlDbType.Bit);
					parameterSendNewsletter.Value = sendNewsletter;
					myCommand.Parameters.Add(parameterSendNewsletter);
					// Execute the command
					myConnection.Open();

					try
					{
						myCommand.ExecuteNonQuery();
					}

					finally
					{
						myConnection.Close();
					}
				}
			}
		}

		/// <summary>
		/// The UpdateUser method updates a user record from the "Users" database table.
		/// </summary>
		/// <param name="userID"></param>
		/// <param name="name"></param>
		/// <param name="email"></param>
		/// <param name="password"></param>
		/// <param name="portalID"></param>
		/// <param name="SendNewsletter"></param>
		public void UpdateUser(int userID, String name, String email, String password, int portalID, bool sendNewsletter)
		{
			if (PortalSettings.UseSingleUserBase) portalID = 0;

			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_UpdateUser", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Add Parameters to SPROC
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
					parameterUserID.Value = userID;
					myCommand.Parameters.Add(parameterUserID);
					SqlParameter parameterName = new SqlParameter("@Name", SqlDbType.NVarChar, 50);
					parameterName.Value = name;
					myCommand.Parameters.Add(parameterName);
					SqlParameter parameterEmail = new SqlParameter("@Email", SqlDbType.NVarChar, 100);
					parameterEmail.Value = email;
					myCommand.Parameters.Add(parameterEmail);
					SqlParameter parameterPassword = new SqlParameter("@Password", SqlDbType.NVarChar, 20);
					parameterPassword.Value = password;
					myCommand.Parameters.Add(parameterPassword);
					SqlParameter parameterSendNewsletter = new SqlParameter("@SendNewsletter", SqlDbType.Bit);
					parameterSendNewsletter.Value = sendNewsletter;
					myCommand.Parameters.Add(parameterSendNewsletter);

					// Execute the command in a try/catch to catch duplicate username errors
					try
					{
						// Open the connection and execute the Command
						myConnection.Open();
						myCommand.ExecuteNonQuery();
					}

					catch
					{
						throw;
					}

					finally
					{
						// Close the Connection
						if (myConnection.State == ConnectionState.Open)
							myConnection.Close();
					}
				}
			}
		}

		// method added by Thierry (tiptopweb) on 12 April 2003
		/// <summary>
		/// The UpdateUser method inserts a new user record into the "Users" database table.
		/// </summary>
		/// <param name="userID"></param>
		/// <param name="Name"></param>
		/// <param name="Company"></param>
		/// <param name="Address"></param>
		/// <param name="City"></param>
		/// <param name="Zip"></param>
		/// <param name="Phone"></param>
		/// <param name="Fax"></param>
		/// <param name="PIva"></param>
		/// <param name="CFiscale"></param>
		/// <param name="SendNewsletter"></param>
		/// <param name="IDCountry"></param>
		/// <param name="IDState"></param>
		/// <returns></returns>
		public void UpdateUser(int userID, String name, String company, String address, String city, String zip, String phone, String fax, String pIva, String cFiscale, bool sendNewsletter, string iDCountry, int iDState)
		{
			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("UpdateUserFullNoPassword", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Add Parameters to SPROC
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
					parameterUserID.Value = userID;
					myCommand.Parameters.Add(parameterUserID);
					SqlParameter parameterIDState = new SqlParameter("@StateID", SqlDbType.Int);
					parameterIDState.Value = iDState;
					myCommand.Parameters.Add(parameterIDState);
					SqlParameter parameterIDCountry = new SqlParameter("@CountryID", SqlDbType.NChar, 2);
					parameterIDCountry.Value = iDCountry;
					myCommand.Parameters.Add(parameterIDCountry);
					SqlParameter parameterName = new SqlParameter("@Name", SqlDbType.NVarChar, 50);
					parameterName.Value = name;
					myCommand.Parameters.Add(parameterName);
					SqlParameter parameterAddress = new SqlParameter("@Address", SqlDbType.NVarChar, 50);
					parameterAddress.Value = address;
					myCommand.Parameters.Add(parameterAddress);
					SqlParameter parameterCompany = new SqlParameter("@Company", SqlDbType.NVarChar, 50);
					parameterCompany.Value = company;
					myCommand.Parameters.Add(parameterCompany);
					SqlParameter parameterCity = new SqlParameter("@City", SqlDbType.NVarChar, 50);
					parameterCity.Value = city;
					myCommand.Parameters.Add(parameterCity);
					SqlParameter parameterZip = new SqlParameter("@Zip", SqlDbType.NVarChar, 6);
					parameterZip.Value = zip;
					myCommand.Parameters.Add(parameterZip);
					SqlParameter parameterPIva = new SqlParameter("@PIva", SqlDbType.NVarChar, 11);
					parameterPIva.Value = pIva;
					myCommand.Parameters.Add(parameterPIva);
					SqlParameter parameterCFiscale = new SqlParameter("@CFiscale", SqlDbType.NVarChar, 16);
					parameterCFiscale.Value = cFiscale;
					myCommand.Parameters.Add(parameterCFiscale);
					SqlParameter parameterPhone = new SqlParameter("@Phone", SqlDbType.NVarChar, 50);
					parameterPhone.Value = phone;
					myCommand.Parameters.Add(parameterPhone);
					SqlParameter parameterFax = new SqlParameter("@Fax", SqlDbType.NVarChar, 50);
					parameterFax.Value = fax;
					myCommand.Parameters.Add(parameterFax);
					SqlParameter parameterSendNewsletter = new SqlParameter("@SendNewsletter", SqlDbType.Bit);
					parameterSendNewsletter.Value = sendNewsletter;
					myCommand.Parameters.Add(parameterSendNewsletter);

					// Execute the command in a try/catch to catch duplicate username errors
					try
					{
						// Open the connection and execute the Command
						myConnection.Open();
						myCommand.ExecuteNonQuery();
					}

					catch
					{
						throw;
					}

					finally
					{
						// Close the Connection
						if (myConnection.State == ConnectionState.Open)
							myConnection.Close();
					}
				}
			}
		}

		/// <summary>
		/// The UpdateUserCheckEmail sets the user email as trusted and verified
		/// </summary>
		/// <param name="userID"></param>
		/// <param name="CheckedEmail"></param>
		public void UpdateUserCheckEmail(int userID, int checkedEmail)
		{
			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_UpdateUserCheckEmail", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Add Parameters to SPROC
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
					parameterUserID.Value = userID;
					myCommand.Parameters.Add(parameterUserID);
					SqlParameter parameterCheckedEmail = new SqlParameter("@CheckedEmail", SqlDbType.TinyInt);
					parameterCheckedEmail.Value = checkedEmail;
					myCommand.Parameters.Add(parameterCheckedEmail);
					// Open the database connection and execute the command
					myConnection.Open();

					try
					{
						myCommand.ExecuteNonQuery();
					}

					finally
					{
						myConnection.Close();
					}
				}
			}
		}

		/// <summary>
		/// Change the user password with a new one
		/// </summary>
		/// <param name="userID"></param>
		/// <param name="Password"></param>
		public void UpdateUserSetPassword(int userID, string password)
		{
			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_UpdateUserSetPassword", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Add Parameters to SPROC
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
					parameterUserID.Value = userID;
					myCommand.Parameters.Add(parameterUserID);
					SqlParameter parameterPassword = new SqlParameter("@Password", SqlDbType.NVarChar, 20);
					parameterPassword.Value = password;
					myCommand.Parameters.Add(parameterPassword);
					// Open the database connection and execute the command
					myConnection.Open();

					try
					{
						myCommand.ExecuteNonQuery();
					}

					finally
					{
						myConnection.Close();
					}
				}
			}
		}
	}

	/// <summary>
	///*********************************************************************
	/// [START -- Added for User 's WIndow Mgmt -- bja@reedtek.com]
	///
	/// UserWinMgmtDB Class
	///
	/// The UserWinMgmtDB class encapsulates all data logic necessary to add/delete/query
	/// users window mgmt level ( min/max/close )
	///
	///
	///*********************************************************************
	/// </summary>
	public sealed class UserWinMgmtDB
	{
		/// <summary>
		///*********************************************************************
		///
		/// DeleteUserDeskTop Method
		///
		/// The DeleteUserDeskTop method deletes a specific user desktop from the serDesktop database table.
		///
		///*********************************************************************
		/// </summary>
		/// <param name="userID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <param name="portalID" type="int">
		///     <para>
		///         
		///     </para>
		/// </param>
		/// <returns>
		///     A bool value...
		/// </returns>
		public bool DeleteUserDeskTop(int userID, int portalID)
		{
			bool results = false;

			// john.mandia@whitelightsolutions.com: 29th May 2004: Since this has to do with collapsable modules on a specific tab on a specific portal I don't think it should pass the static portal ID
			//if (PortalSettings.UseSingleUserBase) portalID = 0;
			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_DeleteUserDesktop", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Update Parameters to SPROC
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
					parameterUserID.Value = userID;
					myCommand.Parameters.Add(parameterUserID);
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);

					try
					{
						// Execute the command
						myConnection.Open();
						myCommand.ExecuteNonQuery();
						results = true;
					}

					catch
					{
					}

					finally
					{
						myConnection.Close();
					}
					// Return the status
					return results;
				}
			}
		} // end of DeleteUserDeskTop

		/// <summary>
		/// GetUserDesktop() Method <a name="GetUserDesktop"></a>
		///
		/// The GetUserDesktop method returns a list of the users' desktop envrionment
		///
		/// Other relevant sources:
		///     + <a href="GetUserDesktop.htm" style="color:green">GetUserDesktop Stored Procedure</a>
		/// </summary>
		/// <param name="userID"></param>
		/// <param name="portalID"></param>
		/// <returns></returns>
		public UserLayoutMgr GetUserDesktop(int userID, int portalID)
		{
			UserLayoutMgr ulm = new UserLayoutMgr();

			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_GetUserDesktop", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
					parameterUserID.Value = userID;
					myCommand.Parameters.Add(parameterUserID);
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);
					SqlDataReader dr = null;

					try
					{
						// Open the database connection and execute the command
						myConnection.Open();
						dr = myCommand.ExecuteReader(CommandBehavior.CloseConnection);

						// valid data
						if (dr != null)
							// populate the data w/ what we want
							populateUserLayoutMgr(ref dr, ref ulm);
					}

					catch
					{
					}

					finally
					{
						if (dr != null)
							dr.Close();
					}
					// Return the datareader
					return ulm;
				}
			}
		} // end of GetUserDesktop

		/// <summary>
		/// Save the User's Window Desktop Settings
		/// </summary>
		/// <param name="portalID"></param>
		/// <param name="userID"></param>
		/// <param name="moduleID"></param>
		/// <param name="tabID"></param>
		/// <param name="wstate"></param>
		public void SaveUserDesktop(int portalID, int userID, int moduleID, int tabID, WindowStateEnum wstate)
		{
			// john.mandia@whitelightsolutions.com: 29th May 2004: Since this has to do with collapsable modules on a specific tab on a specific portal I don't think it should pass the static portal ID
			//if (PortalSettings.UseSingleUserBase) portalID = 0;
			// Create Instance of Connection and Command Object
			using (SqlConnection myConnection = PortalSettings.SqlConnectionString)
			{
				using (SqlCommand myCommand = new SqlCommand("rb_UpdateUserDesktop", myConnection))
				{
					// Mark the Command as a SPROC
					myCommand.CommandType = CommandType.StoredProcedure;
					// Update Parameters to SPROC
					SqlParameter parameterUserID = new SqlParameter("@UserID", SqlDbType.Int);
					parameterUserID.Value = userID;
					myCommand.Parameters.Add(parameterUserID);
					SqlParameter parameterPortalID = new SqlParameter("@PortalID", SqlDbType.Int);
					parameterPortalID.Value = portalID;
					myCommand.Parameters.Add(parameterPortalID);
					SqlParameter parameterModuleID = new SqlParameter("@ModuleID", SqlDbType.Int);
					parameterModuleID.Value = moduleID;
					myCommand.Parameters.Add(parameterModuleID);
					SqlParameter parameterTabID = new SqlParameter("@TabID", SqlDbType.Int);
					parameterTabID.Value = tabID;
					myCommand.Parameters.Add(parameterTabID);
					SqlParameter parameterState = new SqlParameter("@WindowState", SqlDbType.SmallInt);
					parameterState.Value = (short) wstate;
					myCommand.Parameters.Add(parameterState);
					// Execute the command
					myConnection.Open();

					try
					{
						myCommand.ExecuteNonQuery();
					}

					finally
					{
						myConnection.Close();
					}
				}
			}
		} // end of SaveUserDesktop

		#region Private Methods

		/// <summary>
		/// Create the Module Settings 
		/// </summary>
		/// <param name="dr"></param>
		/// <returns></returns>
		private UserModuleSettings addModuleSettings(ref SqlDataReader dr)
		{
			UserModuleSettings ums = new UserModuleSettings();

			try
			{
				string name = string.Empty;

				// iterate over the fields/columns
				for (int inx = 0; inx < dr.FieldCount; ++inx)
				{
					// get the values
					if (!dr.IsDBNull(inx))
					{
						name = dr.GetName(inx).ToLower();

						if (name[0] == 'm') // module id
							ums.ModuleID = dr.GetInt32(inx);

						else if (name[0] == 't') // tab id
							ums.TabID = dr.GetInt32(inx);

						else if (name[0] == 's') // Window State
							ums.State = (WindowStateEnum) dr.GetInt16(inx);
					}
				}
			} 
#if ! DEBUG

			catch
			{
			}
#else

			catch (Exception ex)
			{
				throw ex;
			}
#endif
			return ums;
		} // end of addModuleSettings

		/// <summary>
		/// Populate a User Layout from the Data Reader
		/// </summary>
		/// <param name="dr"></param>
		/// <param name="ulm"></param>
		private void populateUserLayoutMgr(ref SqlDataReader dr, ref UserLayoutMgr ulm)
		{
			while (dr.Read())
				ulm.Add(addModuleSettings(ref dr));
			//do not close here...!!!
		} // end of populateUserLayoutMgr

		#endregion
	} // end of UserWinMgmtDB
	//*********************************************************************
	// [END -- Added for User 's WIndow Mgmt -- bja@reedtek.com]
	//
	//*********************************************************************
}