<?xml version="1.0" encoding="utf-8"?>
<Database Name="Database" EntityNamespace="Rainbow.Framework.Data.MsSql" ContextNamespace="Rainbow.Framework.Data.MsSql" Class="DataClassesDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=&quot;T:\Users\William Forney\Desktop\Rainbow\WebSites\Rainbow\App_Data\Database.mdf&quot;;Integrated Security=True;Asynchronous Processing=True;MultipleActiveResultSets=True;Connect Timeout=30;User Instance=True" SettingsObjectName="Rainbow.Framework.Data.MsSql.Properties.Settings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_Membership" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_Membership1" Member="aspnet_Membership1" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
      <Association Name="aspnet_User_User" Member="Users" ThisKey="UserId,UserName,LastActivityDate" OtherKey="UserId,UserName,LastActivityDate" Type="User" />
      <Association Name="aspnet_Application_aspnet_User" Member="aspnet_Application" ThisKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
      <Association Name="aspnet_Application_aspnet_User1" Member="aspnet_Application1" ThisKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Memberships">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_Membership_User" Member="Users" ThisKey="Email,PasswordQuestion,Comment,IsApproved,CreateDate,LastLoginDate,LastPasswordChangedDate,UserId,IsLockedOut,LastLockoutDate" OtherKey="Email,PasswordQuestion,Comment,IsApproved,CreationDate,LastLoginDate,LastPasswordChangedDate,UserId,IsLockedOut,LastLockedOutDate" Type="User" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_User" ThisKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_Membership1" Member="aspnet_User1" ThisKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="aspnet_Application_aspnet_Membership" Member="aspnet_Application" ThisKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
      <Association Name="aspnet_Application_aspnet_Membership1" Member="aspnet_Application1" ThisKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="Users">
    <Type Name="User" Id="ID1">
      <Column Name="UserName" Type="System.String" CanBeNull="false" />
      <Column Name="Email" Type="System.String" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" CanBeNull="false" />
      <Column Name="LastLockedOutDate" Type="System.DateTime" CanBeNull="false" />
      <Association Name="aspnet_User_User" Member="aspnet_User" ThisKey="UserId,UserName,LastActivityDate" OtherKey="UserId,UserName,LastActivityDate" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="aspnet_Membership_User" Member="aspnet_Membership" ThisKey="Email,PasswordQuestion,Comment,IsApproved,CreationDate,LastLoginDate,LastPasswordChangedDate,UserId,IsLockedOut,LastLockedOutDate" OtherKey="Email,PasswordQuestion,Comment,IsApproved,CreateDate,LastLoginDate,LastPasswordChangedDate,UserId,IsLockedOut,LastLockoutDate" Type="aspnet_Membership" IsForeignKey="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId1">
      <Argument Parameter="userName" Member="UserName" />
      <Argument Parameter="email" Member="Email" />
      <Argument Parameter="passwordQuestion" Member="PasswordQuestion" />
      <Argument Parameter="isApproved" Member="IsApproved" />
      <Argument Parameter="createDate" Member="CreationDate" />
      <Argument Parameter="userId" Member="UserId" />
    </InsertFunction>
    <UpdateFunction FunctionId="FunctionId2">
      <Argument Parameter="userName" Member="UserName" />
      <Argument Parameter="email" Member="Email" />
      <Argument Parameter="comment" Member="Comment" />
      <Argument Parameter="isApproved" Member="IsApproved" />
      <Argument Parameter="lastLoginDate" Member="LastLoginDate" />
      <Argument Parameter="lastActivityDate" Member="LastActivityDate" />
    </UpdateFunction>
  </Table>
  <Table Name="dbo.aspnet_Applications" Member="aspnet_Applications">
    <Type Name="aspnet_Application">
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Application_aspnet_User" Member="aspnet_Users" OtherKey="ApplicationId" Type="aspnet_User" />
      <Association Name="aspnet_Application_aspnet_User1" Member="aspnet_Users1" OtherKey="ApplicationId" Type="aspnet_User" />
      <Association Name="aspnet_Application_aspnet_Membership" Member="aspnet_Memberships" OtherKey="ApplicationId" Type="aspnet_Membership" />
      <Association Name="aspnet_Application_aspnet_Membership1" Member="aspnet_Memberships1" OtherKey="ApplicationId" Type="aspnet_Membership" />
    </Type>
  </Table>
  <Function Name="dbo.aspnet_Membership_ChangePasswordQuestionAndAnswer" Method="aspnet_Membership_ChangePasswordQuestionAndAnswer">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="NewPasswordQuestion" Parameter="newPasswordQuestion" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="NewPasswordAnswer" Parameter="newPasswordAnswer" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_UpdateUserInfo" Method="aspnet_Membership_UpdateUserInfo">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="IsPasswordCorrect" Parameter="isPasswordCorrect" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UpdateLastLoginActivityDate" Parameter="updateLastLoginActivityDate" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="MaxInvalidPasswordAttempts" Parameter="maxInvalidPasswordAttempts" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordAttemptWindow" Parameter="passwordAttemptWindow" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="LastLoginDate" Parameter="lastLoginDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="LastActivityDate" Parameter="lastActivityDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId1" Name="dbo.aspnet_Membership_CreateUser" Method="aspnet_Membership_CreateUser">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="PasswordSalt" Parameter="passwordSalt" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PasswordQuestion" Parameter="passwordQuestion" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="PasswordAnswer" Parameter="passwordAnswer" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="IsApproved" Parameter="isApproved" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="CreateDate" Parameter="createDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UniqueEmail" Parameter="uniqueEmail" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordFormat" Parameter="passwordFormat" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_GetNumberOfUsersOnline" Method="aspnet_Membership_GetNumberOfUsersOnline">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="MinutesSinceLastInActive" Parameter="minutesSinceLastInActive" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_GetPassword" Method="aspnet_Membership_GetPassword">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="MaxInvalidPasswordAttempts" Parameter="maxInvalidPasswordAttempts" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordAttemptWindow" Parameter="passwordAttemptWindow" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PasswordAnswer" Parameter="passwordAnswer" Type="System.String" DbType="NVarChar(128)" />
    <ElementType Name="aspnet_Membership_GetPasswordResult">
      <Column Name="Column1" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Column2" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Membership_GetPasswordWithFormat" Method="aspnet_Membership_GetPasswordWithFormat">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UpdateLastLoginActivityDate" Parameter="updateLastLoginActivityDate" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="aspnet_Membership_GetPasswordWithFormatResult">
      <Column Name="Column1" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Column2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Column3" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Column4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Column5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Column6" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Column7" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Column8" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Membership_GetUserByEmail" Method="aspnet_Membership_GetUserByEmail">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="aspnet_Membership_GetUserByEmailResult">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.aspnet_Membership_GetUserByName" Method="aspnet_Membership_GetUserByName">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UpdateLastActivity" Parameter="updateLastActivity" Type="System.Boolean" DbType="Bit" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.aspnet_Membership_GetUserByUserId" Method="aspnet_Membership_GetUserByUserId">
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UpdateLastActivity" Parameter="updateLastActivity" Type="System.Boolean" DbType="Bit" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.aspnet_Membership_ResetPassword" Method="aspnet_Membership_ResetPassword">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="NewPassword" Parameter="newPassword" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="MaxInvalidPasswordAttempts" Parameter="maxInvalidPasswordAttempts" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordAttemptWindow" Parameter="passwordAttemptWindow" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordSalt" Parameter="passwordSalt" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PasswordFormat" Parameter="passwordFormat" Type="System.Int32" DbType="Int" />
    <Parameter Name="PasswordAnswer" Parameter="passwordAnswer" Type="System.String" DbType="NVarChar(128)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_SetPassword" Method="aspnet_Membership_SetPassword">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="NewPassword" Parameter="newPassword" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="PasswordSalt" Parameter="passwordSalt" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PasswordFormat" Parameter="passwordFormat" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Membership_UnlockUser" Method="aspnet_Membership_UnlockUser">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId2" Name="dbo.aspnet_Membership_UpdateUser" Method="aspnet_Membership_UpdateUser">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Comment" Parameter="comment" Type="System.String" DbType="NText" />
    <Parameter Name="IsApproved" Parameter="isApproved" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LastLoginDate" Parameter="lastLoginDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="LastActivityDate" Parameter="lastActivityDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UniqueEmail" Parameter="uniqueEmail" Type="System.Int32" DbType="Int" />
    <Parameter Name="CurrentTimeUtc" Parameter="currentTimeUtc" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.aspnet_Users_DeleteUser" Method="aspnet_Users_DeleteUser">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="TablesToDeleteFrom" Parameter="tablesToDeleteFrom" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumTablesDeletedFrom" Parameter="numTablesDeletedFrom" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>