
		
//========================================================================
// This file was generated using the MyGeneration tool in combination
// with the Gentle.NET Business Entity template, $Rev: 44c $
//========================================================================
using System;
using System.Collections;
using Gentle.Framework;

namespace Rainbow.Data.GentleNET
{
	#region rb_Cultures
	/// <summary>
	/// This object represents the properties and methods of a Employee.
	/// </summary>
	[Serializable]
	[TableName("rb_Cultures")]
	public class rb_Cultures : Persistent
	{
		#region Members
		private bool _changed = false;
		private static bool invalidatedListAll = true;
		private static ArrayList listAllCache = null;
		[TableColumn("CultureCode", NotNull=true), PrimaryKey(AutoGenerated=false)]
		protected string cultureCode;
		[TableColumn("NeutralCode")]
		protected string neutralCode;
		[TableColumn("CountryID"), ForeignKey("rb_Countries", "CountryID")]
		protected string countryID;
		[TableColumn("Description")]
		protected string description;
		[TableColumn("Identifier", NotNull=true)]
		protected int identifier;
		#endregion
			

		#region Constructors
	

		/// <summary> 
		/// Create a new object using the minimum required information (all not-null fields except 
		/// auto-generated primary keys). 
		/// </summary> 
		public rb_Cultures( 
				string CultureCode, 
				int Identifier)
		{
			_changed = true;
			invalidatedListAll = true;
			cultureCode = CultureCode;
			identifier = Identifier;
		}

			
		/// <summary> 
		/// Create an object from an existing row of data. This will be used by Gentle to 
		/// construct objects from retrieved rows. 
		/// </summary> 
		public rb_Cultures( 
				string CultureCode, 
				string NeutralCode, 
				string CountryID, 
				string Description, 
				int Identifier)
		{
			cultureCode = CultureCode;
			neutralCode = NeutralCode;
			countryID = CountryID;
			description = Description;
			identifier = Identifier;
		}

		#endregion

		#region Public Properties
		
		public bool Changed
		{ get { return _changed; } }
		
		public string CultureCode
		{
			get{ return cultureCode != null ?cultureCode.TrimEnd() : null; }
			set{ _changed |= cultureCode != value; cultureCode = value; invalidatedListAll =  _changed;}
		}
		
		public string NeutralCode
		{
			get{ return neutralCode != null ?neutralCode.TrimEnd() : null; }
			set{ _changed |= neutralCode != value; neutralCode = value; invalidatedListAll =  _changed;}
		}
		
		public string CountryID
		{
			get{ return countryID != null ?countryID.TrimEnd() : null; }
			set{ _changed |= countryID != value; countryID = value; invalidatedListAll =  _changed;}
		}
		
		public string Description
		{
			get{ return description != null ?description.TrimEnd() : null; }
			set{ _changed |= description != value; description = value; invalidatedListAll =  _changed;}
		}
		
		public int Identifier
		{
			get{ return identifier; }
			set{ _changed |= identifier != value; identifier = value; invalidatedListAll =  _changed;}
		}
		
	
		// generate a static property to retrieve all instances of a class that are stored in the database
		static public IList ListAll
		{
			get 
			{ 
				if( listAllCache == null || invalidatedListAll )
				{
					listAllCache = Broker.RetrieveList( typeof(rb_Cultures) ) as ArrayList;
					invalidatedListAll = false;
				}
				return listAllCache;
			}
		}
		
		#endregion

		#region Debug Properties
		/// <summary>
		/// Generated only when genDebug flag enabled in MyGeneration template UI
		/// Returns number of items in internal cache
		/// </summary>
		public static int CacheCount
		{
			get{ return listAllCache == null ? 0 : listAllCache.Count;}
		}
		
		#endregion

		#region Storage and retrieval
	   
		public static rb_Cultures Retrieve(string id )
		{
		  
			Key key = new Key( typeof(rb_Cultures), true, "CultureCode", id );
			return Broker.RetrieveInstance( typeof(rb_Cultures), key ) as rb_Cultures;
		}

		//Gentle.NET Business Entity script: Generation of complex retrieve function (multiple primary keys) is not implemented yet.

		public override void Persist()
		{
			if( Changed || !IsPersisted )
			{
				base.Persist();
				_changed=false;
			}
		}

		public override void Remove()
		{
			base.Remove();
			invalidatedListAll = true;
		}
		#endregion

		#region Relations
		// List of primary keys for this class table
		// Key: CultureCode
		// List of foreign keys for this class table
		// Key: FK_rb_Cultures_rb_Countries primary table: rb_Countries primary column: CountryID foreign column: CountryID foreign table: rb_Cultures
		// List of selected relation tables for this database
		// Table: rb_Announcements
		// Table: rb_Announcements_st
		// Table: rb_Articles
		// Table: rb_Blacklist
		// Table: rb_BlogComments
		// Table: rb_Blogs
		// Table: rb_BlogStats
		// Table: rb_BookList
		// Table: rb_ComponentModule
		// Table: rb_Contacts
		// Table: rb_Contacts_st
		// Table: rb_ContentManager
		// Table: rb_Countries
		// Table: rb_Cultures
		// Table: rb_Discussion
		// Table: rb_Documents
		// Table: rb_Documents_st
		// Table: rb_EnhancedHtml
		// Table: rb_EnhancedHtml_st
		// Table: rb_EnhancedLinks
		// Table: rb_EnhancedLinks_st
		// Table: rb_Events
		// Table: rb_Events_st
		// Table: rb_FAQs
		// Table: rb_GeneralModuleDefinitions
		// Table: rb_HtmlText
		// Table: rb_HtmlText_st
		// Table: rb_Links
		// Table: rb_Links_st
		// Table: rb_Localize
		// Table: rb_Milestones
		// Table: rb_Milestones_st
		// Table: rb_ModuleDefinitions
		// Table: rb_Modules
		// Table: rb_ModuleSettings
		// Table: rb_Monitoring
		// Table: rb_Pictures
		// Table: rb_Pictures_st
		// Table: rb_Portals
		// Table: rb_PortalSettings
		// Table: rb_Roles
		// Table: rb_SolutionModuleDefinitions
		// Table: rb_Solutions
		// Table: rb_States
		// Table: rb_SurveyAnswers
		// Table: rb_SurveyOptions
		// Table: rb_SurveyQuestions
		// Table: rb_Surveys
		// Table: rb_Tabs
		// Table: rb_TabSettings
		// Table: rb_Tasks
		// Table: rb_UserDefinedData
		// Table: rb_UserDefinedFields
		// Table: rb_UserDefinedRows
		// Table: rb_UserDesktop
		// Table: rb_UserRoles
		// Table: rb_Users
		// Table: rb_Versions

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Countries", using relation table "rb_Cultures"
		/// </summary>
		public IList referencedrb_CountriesUsingrb_Cultures()
		{
			return new GentleList( typeof(rb_Countries), this, typeof(rb_Cultures));
		}
		#endregion

		#region ManualCode
/***PRESERVE_BEGIN MANUAL_CODE***//***PRESERVE_END MANUAL_CODE***/
		#endregion
	}

}
#endregion


