
		
//========================================================================
// This file was generated using the MyGeneration tool in combination
// with the Gentle.NET Business Entity template, $Rev: 44 $
//========================================================================
using System;
using System.Collections;
using Gentle.Framework;

namespace Rainbow.Data.GentleNET
{
	#region rb_Modules
	/// <summary>
	/// This object represents the properties and methods of a Employee.
	/// </summary>
	[Serializable]
	[TableName("rb_Modules")]
	public class rb_Modules : Persistent
	{
		#region Members
		private bool _changed = false;
		private static bool invalidatedListAll = true;
		private static ArrayList listAllCache = null;
		[TableColumn("ModuleID", NotNull=true), PrimaryKey(AutoGenerated=true)]
		protected int moduleID;
		[TableColumn("TabID", NotNull=true), ForeignKey("rb_Tabs", "TabID")]
		protected int tabID;
		[TableColumn("ModuleDefID", NotNull=true), ForeignKey("rb_ModuleDefinitions", "ModuleDefID")]
		protected int moduleDefID;
		[TableColumn("ModuleOrder", NotNull=true)]
		protected int moduleOrder;
		[TableColumn("PaneName", NotNull=true)]
		protected string paneName;
		[TableColumn("ModuleTitle")]
		protected string moduleTitle;
		[TableColumn("AuthorizedEditRoles")]
		protected string authorizedEditRoles;
		[TableColumn("AuthorizedViewRoles")]
		protected string authorizedViewRoles;
		[TableColumn("AuthorizedAddRoles")]
		protected string authorizedAddRoles;
		[TableColumn("AuthorizedDeleteRoles")]
		protected string authorizedDeleteRoles;
		[TableColumn("AuthorizedPropertiesRoles")]
		protected string authorizedPropertiesRoles;
		[TableColumn("CacheTime", NotNull=true)]
		protected int cacheTime;
		[TableColumn("ShowMobile")]
		protected bool showMobile;
		[TableColumn("AuthorizedPublishingRoles")]
		protected string authorizedPublishingRoles;
		[TableColumn("NewVersion")]
		protected bool newVersion;
		[TableColumn("SupportWorkflow")]
		protected bool supportWorkflow;
		[TableColumn("AuthorizedApproveRoles")]
		protected string authorizedApproveRoles;
		[TableColumn("WorkflowState")]
		protected byte workflowState;
		[TableColumn("LastModified")]
		protected DateTime lastModified;
		[TableColumn("LastEditor")]
		protected string lastEditor;
		[TableColumn("StagingLastModified")]
		protected DateTime stagingLastModified;
		[TableColumn("StagingLastEditor")]
		protected string stagingLastEditor;
		[TableColumn("SupportCollapsable")]
		protected bool supportCollapsable;
		[TableColumn("ShowEveryWhere")]
		protected bool showEveryWhere;
		[TableColumn("AuthorizedMoveModuleRoles")]
		protected string authorizedMoveModuleRoles;
		[TableColumn("AuthorizedDeleteModuleRoles")]
		protected string authorizedDeleteModuleRoles;
		#endregion
			

		#region Constructors
	

		/// <summary> 
		/// Create a new object using the minimum required information (all not-null fields except 
		/// auto-generated primary keys). 
		/// </summary> 
		public rb_Modules( 
				int TabID, 
				int ModuleDefID, 
				int ModuleOrder, 
				string PaneName, 
				int CacheTime)
		{
			_changed = true;
			invalidatedListAll = true;
			moduleID = 0;
			tabID = TabID;
			moduleDefID = ModuleDefID;
			moduleOrder = ModuleOrder;
			paneName = PaneName;
			cacheTime = CacheTime;
		}


		/// <summary> 
		/// Create a new object by specifying all fields (except the auto-generated primary key field). 
		/// </summary> 
		public rb_Modules( 
				int TabID, 
				int ModuleDefID, 
				int ModuleOrder, 
				string PaneName, 
				string ModuleTitle, 
				string AuthorizedEditRoles, 
				string AuthorizedViewRoles, 
				string AuthorizedAddRoles, 
				string AuthorizedDeleteRoles, 
				string AuthorizedPropertiesRoles, 
				int CacheTime, 
				bool ShowMobile, 
				string AuthorizedPublishingRoles, 
				bool NewVersion, 
				bool SupportWorkflow, 
				string AuthorizedApproveRoles, 
				byte WorkflowState, 
				DateTime LastModified, 
				string LastEditor, 
				DateTime StagingLastModified, 
				string StagingLastEditor, 
				bool SupportCollapsable, 
				bool ShowEveryWhere, 
				string AuthorizedMoveModuleRoles, 
				string AuthorizedDeleteModuleRoles)
		{
			_changed = true;
			invalidatedListAll = true;
			tabID = TabID;
			moduleDefID = ModuleDefID;
			moduleOrder = ModuleOrder;
			paneName = PaneName;
			moduleTitle = ModuleTitle;
			authorizedEditRoles = AuthorizedEditRoles;
			authorizedViewRoles = AuthorizedViewRoles;
			authorizedAddRoles = AuthorizedAddRoles;
			authorizedDeleteRoles = AuthorizedDeleteRoles;
			authorizedPropertiesRoles = AuthorizedPropertiesRoles;
			cacheTime = CacheTime;
			showMobile = ShowMobile;
			authorizedPublishingRoles = AuthorizedPublishingRoles;
			newVersion = NewVersion;
			supportWorkflow = SupportWorkflow;
			authorizedApproveRoles = AuthorizedApproveRoles;
			workflowState = WorkflowState;
			lastModified = LastModified;
			lastEditor = LastEditor;
			stagingLastModified = StagingLastModified;
			stagingLastEditor = StagingLastEditor;
			supportCollapsable = SupportCollapsable;
			showEveryWhere = ShowEveryWhere;
			authorizedMoveModuleRoles = AuthorizedMoveModuleRoles;
			authorizedDeleteModuleRoles = AuthorizedDeleteModuleRoles;
		}

			
		/// <summary> 
		/// Create an object from an existing row of data. This will be used by Gentle to 
		/// construct objects from retrieved rows. 
		/// </summary> 
		public rb_Modules( 
				int ModuleID, 
				int TabID, 
				int ModuleDefID, 
				int ModuleOrder, 
				string PaneName, 
				string ModuleTitle, 
				string AuthorizedEditRoles, 
				string AuthorizedViewRoles, 
				string AuthorizedAddRoles, 
				string AuthorizedDeleteRoles, 
				string AuthorizedPropertiesRoles, 
				int CacheTime, 
				bool ShowMobile, 
				string AuthorizedPublishingRoles, 
				bool NewVersion, 
				bool SupportWorkflow, 
				string AuthorizedApproveRoles, 
				byte WorkflowState, 
				DateTime LastModified, 
				string LastEditor, 
				DateTime StagingLastModified, 
				string StagingLastEditor, 
				bool SupportCollapsable, 
				bool ShowEveryWhere, 
				string AuthorizedMoveModuleRoles, 
				string AuthorizedDeleteModuleRoles)
		{
			moduleID = ModuleID;
			tabID = TabID;
			moduleDefID = ModuleDefID;
			moduleOrder = ModuleOrder;
			paneName = PaneName;
			moduleTitle = ModuleTitle;
			authorizedEditRoles = AuthorizedEditRoles;
			authorizedViewRoles = AuthorizedViewRoles;
			authorizedAddRoles = AuthorizedAddRoles;
			authorizedDeleteRoles = AuthorizedDeleteRoles;
			authorizedPropertiesRoles = AuthorizedPropertiesRoles;
			cacheTime = CacheTime;
			showMobile = ShowMobile;
			authorizedPublishingRoles = AuthorizedPublishingRoles;
			newVersion = NewVersion;
			supportWorkflow = SupportWorkflow;
			authorizedApproveRoles = AuthorizedApproveRoles;
			workflowState = WorkflowState;
			lastModified = LastModified;
			lastEditor = LastEditor;
			stagingLastModified = StagingLastModified;
			stagingLastEditor = StagingLastEditor;
			supportCollapsable = SupportCollapsable;
			showEveryWhere = ShowEveryWhere;
			authorizedMoveModuleRoles = AuthorizedMoveModuleRoles;
			authorizedDeleteModuleRoles = AuthorizedDeleteModuleRoles;
		}

		#endregion

		#region Public Properties
		
		public bool Changed
		{ get { return _changed; } }
		
		public int ModuleID
		{
			get{ return moduleID; }
		}
		
		public int TabID
		{
			get{ return tabID; }
			set{ _changed |= tabID != value; tabID = value; invalidatedListAll =  _changed;}
		}
		
		public int ModuleDefID
		{
			get{ return moduleDefID; }
			set{ _changed |= moduleDefID != value; moduleDefID = value; invalidatedListAll =  _changed;}
		}
		
		public int ModuleOrder
		{
			get{ return moduleOrder; }
			set{ _changed |= moduleOrder != value; moduleOrder = value; invalidatedListAll =  _changed;}
		}
		
		public string PaneName
		{
			get{ return paneName != null ?paneName.TrimEnd() : null; }
			set{ _changed |= paneName != value; paneName = value; invalidatedListAll =  _changed;}
		}
		
		public string ModuleTitle
		{
			get{ return moduleTitle != null ?moduleTitle.TrimEnd() : null; }
			set{ _changed |= moduleTitle != value; moduleTitle = value; invalidatedListAll =  _changed;}
		}
		
		public string AuthorizedEditRoles
		{
			get{ return authorizedEditRoles != null ?authorizedEditRoles.TrimEnd() : null; }
			set{ _changed |= authorizedEditRoles != value; authorizedEditRoles = value; invalidatedListAll =  _changed;}
		}
		
		public string AuthorizedViewRoles
		{
			get{ return authorizedViewRoles != null ?authorizedViewRoles.TrimEnd() : null; }
			set{ _changed |= authorizedViewRoles != value; authorizedViewRoles = value; invalidatedListAll =  _changed;}
		}
		
		public string AuthorizedAddRoles
		{
			get{ return authorizedAddRoles != null ?authorizedAddRoles.TrimEnd() : null; }
			set{ _changed |= authorizedAddRoles != value; authorizedAddRoles = value; invalidatedListAll =  _changed;}
		}
		
		public string AuthorizedDeleteRoles
		{
			get{ return authorizedDeleteRoles != null ?authorizedDeleteRoles.TrimEnd() : null; }
			set{ _changed |= authorizedDeleteRoles != value; authorizedDeleteRoles = value; invalidatedListAll =  _changed;}
		}
		
		public string AuthorizedPropertiesRoles
		{
			get{ return authorizedPropertiesRoles != null ?authorizedPropertiesRoles.TrimEnd() : null; }
			set{ _changed |= authorizedPropertiesRoles != value; authorizedPropertiesRoles = value; invalidatedListAll =  _changed;}
		}
		
		public int CacheTime
		{
			get{ return cacheTime; }
			set{ _changed |= cacheTime != value; cacheTime = value; invalidatedListAll =  _changed;}
		}
		
		public bool ShowMobile
		{
			get{ return showMobile; }
			set{ _changed |= showMobile != value; showMobile = value; invalidatedListAll =  _changed;}
		}
		
		public string AuthorizedPublishingRoles
		{
			get{ return authorizedPublishingRoles != null ?authorizedPublishingRoles.TrimEnd() : null; }
			set{ _changed |= authorizedPublishingRoles != value; authorizedPublishingRoles = value; invalidatedListAll =  _changed;}
		}
		
		public bool NewVersion
		{
			get{ return newVersion; }
			set{ _changed |= newVersion != value; newVersion = value; invalidatedListAll =  _changed;}
		}
		
		public bool SupportWorkflow
		{
			get{ return supportWorkflow; }
			set{ _changed |= supportWorkflow != value; supportWorkflow = value; invalidatedListAll =  _changed;}
		}
		
		public string AuthorizedApproveRoles
		{
			get{ return authorizedApproveRoles != null ?authorizedApproveRoles.TrimEnd() : null; }
			set{ _changed |= authorizedApproveRoles != value; authorizedApproveRoles = value; invalidatedListAll =  _changed;}
		}
		
		public byte WorkflowState
		{
			get{ return workflowState; }
			set{ _changed |= workflowState != value; workflowState = value; invalidatedListAll =  _changed;}
		}
		
		public DateTime LastModified
		{
			get{ return lastModified; }
			set{ _changed |= lastModified != value; lastModified = value; invalidatedListAll =  _changed;}
		}
		
		public string LastEditor
		{
			get{ return lastEditor != null ?lastEditor.TrimEnd() : null; }
			set{ _changed |= lastEditor != value; lastEditor = value; invalidatedListAll =  _changed;}
		}
		
		public DateTime StagingLastModified
		{
			get{ return stagingLastModified; }
			set{ _changed |= stagingLastModified != value; stagingLastModified = value; invalidatedListAll =  _changed;}
		}
		
		public string StagingLastEditor
		{
			get{ return stagingLastEditor != null ?stagingLastEditor.TrimEnd() : null; }
			set{ _changed |= stagingLastEditor != value; stagingLastEditor = value; invalidatedListAll =  _changed;}
		}
		
		public bool SupportCollapsable
		{
			get{ return supportCollapsable; }
			set{ _changed |= supportCollapsable != value; supportCollapsable = value; invalidatedListAll =  _changed;}
		}
		
		public bool ShowEveryWhere
		{
			get{ return showEveryWhere; }
			set{ _changed |= showEveryWhere != value; showEveryWhere = value; invalidatedListAll =  _changed;}
		}
		
		public string AuthorizedMoveModuleRoles
		{
			get{ return authorizedMoveModuleRoles != null ?authorizedMoveModuleRoles.TrimEnd() : null; }
			set{ _changed |= authorizedMoveModuleRoles != value; authorizedMoveModuleRoles = value; invalidatedListAll =  _changed;}
		}
		
		public string AuthorizedDeleteModuleRoles
		{
			get{ return authorizedDeleteModuleRoles != null ?authorizedDeleteModuleRoles.TrimEnd() : null; }
			set{ _changed |= authorizedDeleteModuleRoles != value; authorizedDeleteModuleRoles = value; invalidatedListAll =  _changed;}
		}
		
	
		// generate a static property to retrieve all instances of a class that are stored in the database
		static public IList ListAll
		{
			get 
			{ 
				if( listAllCache == null || invalidatedListAll )
				{
					listAllCache = Broker.RetrieveList( typeof(rb_Modules) ) as ArrayList;
					invalidatedListAll = false;
				}
				return listAllCache;
			}
		}
		
		#endregion

		#region Debug Properties
		/// <summary>
		/// Generated only when genDebug flag enabled in MyGeneration template UI
		/// Returns number of items in internal cache
		/// </summary>
		public static int CacheCount
		{
			get{ return listAllCache == null ? 0 : listAllCache.Count;}
		}
		
		#endregion

		#region Storage and retrieval
	   
		public static rb_Modules Retrieve(int id )
		{
	   
			// Return null if id is smaller than seed and/or increment for autokey
			if(id<0) 
			{
				return null;
			}
		  
			Key key = new Key( typeof(rb_Modules), true, "ModuleID", id );
			return Broker.RetrieveInstance( typeof(rb_Modules), key ) as rb_Modules;
		}

		//Gentle.NET Business Entity script: Generation of complex retrieve function (multiple primary keys) is not implemented yet.

		public override void Persist()
		{
			if( Changed || !IsPersisted )
			{
				base.Persist();
				_changed=false;
			}
		}

		public override void Remove()
		{
			base.Remove();
			invalidatedListAll = true;
		}
		#endregion

		#region Relations
		// List of primary keys for this class table
		// Key: ModuleID
		// List of foreign keys for this class table
		// Key: FK_rb_Announcements_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Announcements
		// Key: FK_rb_Announcements_st_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Announcements_st
		// Key: FK_rb_Articles_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Articles
		// Key: FK_rbBookListModules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_BookList
		// Key: FK_ComponentModule_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_ComponentModule
		// Key: FK_rb_Contacts_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Contacts
		// Key: FK_rb_Contacts_st_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Contacts_st
		// Key: FK_rb_Discussion_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Discussion
		// Key: FK_rb_Documents_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Documents
		// Key: FK_rb_Documents_st_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Documents_st
		// Key: FK_rb_EnhancedHtml_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_EnhancedHtml
		// Key: FK_rb_EnhancedHtml_st_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_EnhancedHtml_st
		// Key: FK_rb_EnhancedLinks_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_EnhancedLinks
		// Key: FK_rb_EnhancedLinks_st_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_EnhancedLinks_st
		// Key: FK_rb_Events_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Events
		// Key: FK_rb_Events_st_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Events_st
		// Key: FK_rb_HtmlText_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_HtmlText
		// Key: FK_rb_HtmlText_st_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_HtmlText_st
		// Key: FK_rb_Links_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Links
		// Key: FK_rb_Links_st_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Links_st
		// Key: FK_rb_Milestones_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Milestones
		// Key: FK_rb_ModuleSettings_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_ModuleSettings
		// Key: FK_rb_Pictures_rb_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Pictures
		// Key: FK_rb_Surveys_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Surveys
		// Key: FK_Tasks_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_Tasks
		// Key: FK_UserDefinedFields_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_UserDefinedFields
		// Key: FK_UserDefinedRows_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_UserDefinedRows
		// Key: FK_rb_Modules_rb_ModuleDefinitions primary table: rb_ModuleDefinitions primary column: ModuleDefID foreign column: ModuleDefID foreign table: rb_Modules
		// Key: FK_rb_Modules_rb_Tabs primary table: rb_Tabs primary column: TabID foreign column: TabID foreign table: rb_Modules
		// List of selected relation tables for this database
		// Table: rb_Announcements
		// Table: rb_Announcements_st
		// Table: rb_Articles
		// Table: rb_Blacklist
		// Table: rb_BlogComments
		// Table: rb_Blogs
		// Table: rb_BlogStats
		// Table: rb_BookList
		// Table: rb_ComponentModule
		// Table: rb_Contacts
		// Table: rb_Contacts_st
		// Table: rb_ContentManager
		// Table: rb_Countries
		// Table: rb_Cultures
		// Table: rb_Discussion
		// Table: rb_Documents
		// Table: rb_Documents_st
		// Table: rb_EnhancedHtml
		// Table: rb_EnhancedHtml_st
		// Table: rb_EnhancedLinks
		// Table: rb_EnhancedLinks_st
		// Table: rb_Events
		// Table: rb_Events_st
		// Table: rb_FAQs
		// Table: rb_GeneralModuleDefinitions
		// Table: rb_HtmlText
		// Table: rb_HtmlText_st
		// Table: rb_Links
		// Table: rb_Links_st
		// Table: rb_Localize
		// Table: rb_Milestones
		// Table: rb_Milestones_st
		// Table: rb_ModuleDefinitions
		// Table: rb_Modules
		// Table: rb_ModuleSettings
		// Table: rb_Monitoring
		// Table: rb_Pictures
		// Table: rb_Pictures_st
		// Table: rb_Portals
		// Table: rb_PortalSettings
		// Table: rb_Roles
		// Table: rb_SolutionModuleDefinitions
		// Table: rb_Solutions
		// Table: rb_States
		// Table: rb_SurveyAnswers
		// Table: rb_SurveyOptions
		// Table: rb_SurveyQuestions
		// Table: rb_Surveys
		// Table: rb_Tabs
		// Table: rb_TabSettings
		// Table: rb_Tasks
		// Table: rb_UserDefinedData
		// Table: rb_UserDefinedFields
		// Table: rb_UserDefinedRows
		// Table: rb_UserDesktop
		// Table: rb_UserRoles
		// Table: rb_Users
		// Table: rb_Versions

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_SurveyAnswers", using relation table "rb_Surveys"
		/// </summary>
		public IList referencedrb_SurveyAnswersUsingrb_Surveys()
		{
			return new GentleList( typeof(rb_SurveyAnswers), this, typeof(rb_Surveys));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_SurveyQuestions", using relation table "rb_Surveys"
		/// </summary>
		public IList referencedrb_SurveyQuestionsUsingrb_Surveys()
		{
			return new GentleList( typeof(rb_SurveyQuestions), this, typeof(rb_Surveys));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserDefinedData", using relation table "rb_UserDefinedFields"
		/// </summary>
		public IList referencedrb_UserDefinedDataUsingrb_UserDefinedFields()
		{
			return new GentleList( typeof(rb_UserDefinedData), this, typeof(rb_UserDefinedFields));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserDefinedData", using relation table "rb_UserDefinedRows"
		/// </summary>
		public IList referencedrb_UserDefinedDataUsingrb_UserDefinedRows()
		{
			return new GentleList( typeof(rb_UserDefinedData), this, typeof(rb_UserDefinedRows));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Announcements", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_AnnouncementsUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Announcements), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Announcements_st", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_Announcements_stUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Announcements_st), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Articles", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_ArticlesUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Articles), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_BookList", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_BookListUsingrb_Modules()
		{
			return new GentleList( typeof(rb_BookList), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_ComponentModule", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_ComponentModuleUsingrb_Modules()
		{
			return new GentleList( typeof(rb_ComponentModule), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Contacts", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_ContactsUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Contacts), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Contacts_st", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_Contacts_stUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Contacts_st), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Discussion", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_DiscussionUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Discussion), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Documents", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_DocumentsUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Documents), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Documents_st", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_Documents_stUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Documents_st), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_EnhancedHtml", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_EnhancedHtmlUsingrb_Modules()
		{
			return new GentleList( typeof(rb_EnhancedHtml), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_EnhancedHtml_st", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_EnhancedHtml_stUsingrb_Modules()
		{
			return new GentleList( typeof(rb_EnhancedHtml_st), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_EnhancedLinks", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_EnhancedLinksUsingrb_Modules()
		{
			return new GentleList( typeof(rb_EnhancedLinks), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_EnhancedLinks_st", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_EnhancedLinks_stUsingrb_Modules()
		{
			return new GentleList( typeof(rb_EnhancedLinks_st), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Events", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_EventsUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Events), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Events_st", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_Events_stUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Events_st), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_HtmlText", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_HtmlTextUsingrb_Modules()
		{
			return new GentleList( typeof(rb_HtmlText), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_HtmlText_st", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_HtmlText_stUsingrb_Modules()
		{
			return new GentleList( typeof(rb_HtmlText_st), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Links", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_LinksUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Links), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Links_st", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_Links_stUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Links_st), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Milestones", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_MilestonesUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Milestones), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_ModuleSettings", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_ModuleSettingsUsingrb_Modules()
		{
			return new GentleList( typeof(rb_ModuleSettings), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Pictures", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_PicturesUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Pictures), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Surveys", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_SurveysUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Surveys), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Tasks", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_TasksUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Tasks), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserDefinedFields", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_UserDefinedFieldsUsingrb_Modules()
		{
			return new GentleList( typeof(rb_UserDefinedFields), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserDefinedRows", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_UserDefinedRowsUsingrb_Modules()
		{
			return new GentleList( typeof(rb_UserDefinedRows), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_ModuleDefinitions", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_ModuleDefinitionsUsingrb_Modules()
		{
			return new GentleList( typeof(rb_ModuleDefinitions), this, typeof(rb_Modules));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Tabs", using relation table "rb_Modules"
		/// </summary>
		public IList referencedrb_TabsUsingrb_Modules()
		{
			return new GentleList( typeof(rb_Tabs), this, typeof(rb_Modules));
		}
		#endregion

		#region ManualCode
/***PRESERVE_BEGIN MANUAL_CODE***//***PRESERVE_END MANUAL_CODE***/
		#endregion
	}

}
#endregion


