
		
//========================================================================
// This file was generated using the MyGeneration tool in combination
// with the Gentle.NET Business Entity template, $Rev: 44 $
//========================================================================
using System;
using System.Collections;
using Gentle.Framework;

namespace Rainbow.Data.GentleNET
{
	#region rb_States
	/// <summary>
	/// This object represents the properties and methods of a Employee.
	/// </summary>
	[Serializable]
	[TableName("rb_States")]
	public class rb_States : Persistent
	{
		#region Members
		private bool _changed = false;
		private static bool invalidatedListAll = true;
		private static ArrayList listAllCache = null;
		[TableColumn("StateID", NotNull=true), PrimaryKey(AutoGenerated=false)]
		protected int stateID;
		[TableColumn("Description")]
		protected string description;
		[TableColumn("CountryID", NotNull=true), ForeignKey("rb_Countries", "CountryID")]
		protected string countryID;
		#endregion
			

		#region Constructors
	

		/// <summary> 
		/// Create a new object using the minimum required information (all not-null fields except 
		/// auto-generated primary keys). 
		/// </summary> 
		public rb_States( 
				int StateID, 
				string CountryID)
		{
			_changed = true;
			invalidatedListAll = true;
			stateID = StateID;
			countryID = CountryID;
		}

			
		/// <summary> 
		/// Create an object from an existing row of data. This will be used by Gentle to 
		/// construct objects from retrieved rows. 
		/// </summary> 
		public rb_States( 
				int StateID, 
				string Description, 
				string CountryID)
		{
			stateID = StateID;
			description = Description;
			countryID = CountryID;
		}

		#endregion

		#region Public Properties
		
		public bool Changed
		{ get { return _changed; } }
		
		public int StateID
		{
			get{ return stateID; }
			set{ _changed |= stateID != value; stateID = value; invalidatedListAll =  _changed;}
		}
		
		public string Description
		{
			get{ return description != null ?description.TrimEnd() : null; }
			set{ _changed |= description != value; description = value; invalidatedListAll =  _changed;}
		}
		
		public string CountryID
		{
			get{ return countryID != null ?countryID.TrimEnd() : null; }
			set{ _changed |= countryID != value; countryID = value; invalidatedListAll =  _changed;}
		}
		
	
		// generate a static property to retrieve all instances of a class that are stored in the database
		static public IList ListAll
		{
			get 
			{ 
				if( listAllCache == null || invalidatedListAll )
				{
					listAllCache = Broker.RetrieveList( typeof(rb_States) ) as ArrayList;
					invalidatedListAll = false;
				}
				return listAllCache;
			}
		}
		
		#endregion

		#region Debug Properties
		/// <summary>
		/// Generated only when genDebug flag enabled in MyGeneration template UI
		/// Returns number of items in internal cache
		/// </summary>
		public static int CacheCount
		{
			get{ return listAllCache == null ? 0 : listAllCache.Count;}
		}
		
		#endregion

		#region Storage and retrieval
	   
		public static rb_States Retrieve(int id )
		{
		  
			Key key = new Key( typeof(rb_States), true, "StateID", id );
			return Broker.RetrieveInstance( typeof(rb_States), key ) as rb_States;
		}

		//Gentle.NET Business Entity script: Generation of complex retrieve function (multiple primary keys) is not implemented yet.

		public override void Persist()
		{
			if( Changed || !IsPersisted )
			{
				base.Persist();
				_changed=false;
			}
		}

		public override void Remove()
		{
			base.Remove();
			invalidatedListAll = true;
		}
		#endregion

		#region Relations
		// List of primary keys for this class table
		// Key: StateID
		// List of foreign keys for this class table
		// Key: FK_rb_Users_rb_States primary table: rb_States primary column: StateID foreign column: StateID foreign table: rb_Users
		// Key: FK_rb_States_rb_Countries primary table: rb_Countries primary column: CountryID foreign column: CountryID foreign table: rb_States
		// List of selected relation tables for this database
		// Table: rb_Announcements
		// Table: rb_Announcements_st
		// Table: rb_Articles
		// Table: rb_Blacklist
		// Table: rb_BlogComments
		// Table: rb_Blogs
		// Table: rb_BlogStats
		// Table: rb_BookList
		// Table: rb_ComponentModule
		// Table: rb_Contacts
		// Table: rb_Contacts_st
		// Table: rb_ContentManager
		// Table: rb_Countries
		// Table: rb_Cultures
		// Table: rb_Discussion
		// Table: rb_Documents
		// Table: rb_Documents_st
		// Table: rb_EnhancedHtml
		// Table: rb_EnhancedHtml_st
		// Table: rb_EnhancedLinks
		// Table: rb_EnhancedLinks_st
		// Table: rb_Events
		// Table: rb_Events_st
		// Table: rb_FAQs
		// Table: rb_GeneralModuleDefinitions
		// Table: rb_HtmlText
		// Table: rb_HtmlText_st
		// Table: rb_Links
		// Table: rb_Links_st
		// Table: rb_Localize
		// Table: rb_Milestones
		// Table: rb_Milestones_st
		// Table: rb_ModuleDefinitions
		// Table: rb_Modules
		// Table: rb_ModuleSettings
		// Table: rb_Monitoring
		// Table: rb_Pictures
		// Table: rb_Pictures_st
		// Table: rb_Portals
		// Table: rb_PortalSettings
		// Table: rb_Roles
		// Table: rb_SolutionModuleDefinitions
		// Table: rb_Solutions
		// Table: rb_States
		// Table: rb_SurveyAnswers
		// Table: rb_SurveyOptions
		// Table: rb_SurveyQuestions
		// Table: rb_Surveys
		// Table: rb_Tabs
		// Table: rb_TabSettings
		// Table: rb_Tasks
		// Table: rb_UserDefinedData
		// Table: rb_UserDefinedFields
		// Table: rb_UserDefinedRows
		// Table: rb_UserDesktop
		// Table: rb_UserRoles
		// Table: rb_Users
		// Table: rb_Versions

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserDesktop", using relation table "rb_Users"
		/// </summary>
		public IList referencedrb_UserDesktop()
		{
			return new GentleList( typeof(rb_UserDesktop), this, typeof(rb_Users));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserRoles", using relation table "rb_Users"
		/// </summary>
		public IList referencedrb_UserRoles()
		{
			return new GentleList( typeof(rb_UserRoles), this, typeof(rb_Users));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Countries", using relation table "rb_Users"
		/// </summary>
		public IList referencedrb_CountriesUsers()
		{
			return new GentleList( typeof(rb_Countries), this, typeof(rb_Users));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Portals", using relation table "rb_Users"
		/// </summary>
		public IList referencedrb_Portals()
		{
			return new GentleList( typeof(rb_Portals), this, typeof(rb_Users));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Users", using relation table "rb_States"
		/// </summary>
		public IList referencedrb_Users()
		{
			return new GentleList( typeof(rb_Users), this, typeof(rb_States));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Countries", using relation table "rb_States"
		/// </summary>
		public IList referencedrb_CountriesStates()
		{
			return new GentleList( typeof(rb_Countries), this, typeof(rb_States));
		}
		#endregion

		#region ManualCode
/***PRESERVE_BEGIN MANUAL_CODE***//***PRESERVE_END MANUAL_CODE***/
		#endregion
	}

}
#endregion


