
		
//========================================================================
// This file was generated using the MyGeneration tool in combination
// with the Gentle.NET Business Entity template, $Rev: 44 $
//========================================================================
using System;
using System.Collections;
using Gentle.Framework;

namespace Rainbow.Data.GentleNET
{
	#region rb_UserDefinedFields
	/// <summary>
	/// This object represents the properties and methods of a Employee.
	/// </summary>
	[Serializable]
	[TableName("rb_UserDefinedFields")]
	public class rb_UserDefinedFields : Persistent
	{
		#region Members
		private bool _changed = false;
		private static bool invalidatedListAll = true;
		private static ArrayList listAllCache = null;
		[TableColumn("UserDefinedFieldID", NotNull=true), PrimaryKey(AutoGenerated=true)]
		protected int userDefinedFieldID;
		[TableColumn("ModuleID", NotNull=true), ForeignKey("rb_Modules", "ModuleID")]
		protected int moduleID;
		[TableColumn("FieldTitle", NotNull=true)]
		protected string fieldTitle;
		[TableColumn("Visible", NotNull=true)]
		protected bool visible;
		[TableColumn("FieldOrder", NotNull=true)]
		protected int fieldOrder;
		[TableColumn("FieldType", NotNull=true)]
		protected string fieldType;
		#endregion
			

		#region Constructors
	

		/// <summary> 
		/// Create a new object by specifying all fields (except the auto-generated primary key field). 
		/// </summary> 
		public rb_UserDefinedFields( 
				int ModuleID, 
				string FieldTitle, 
				bool Visible, 
				int FieldOrder, 
				string FieldType)
		{
			_changed = true;
			invalidatedListAll = true;
			moduleID = ModuleID;
			fieldTitle = FieldTitle;
			visible = Visible;
			fieldOrder = FieldOrder;
			fieldType = FieldType;
		}

			
		/// <summary> 
		/// Create an object from an existing row of data. This will be used by Gentle to 
		/// construct objects from retrieved rows. 
		/// </summary> 
		public rb_UserDefinedFields( 
				int UserDefinedFieldID, 
				int ModuleID, 
				string FieldTitle, 
				bool Visible, 
				int FieldOrder, 
				string FieldType)
		{
			userDefinedFieldID = UserDefinedFieldID;
			moduleID = ModuleID;
			fieldTitle = FieldTitle;
			visible = Visible;
			fieldOrder = FieldOrder;
			fieldType = FieldType;
		}

		#endregion

		#region Public Properties
		
		public bool Changed
		{ get { return _changed; } }
		
		public int UserDefinedFieldID
		{
			get{ return userDefinedFieldID; }
		}
		
		public int ModuleID
		{
			get{ return moduleID; }
			set{ _changed |= moduleID != value; moduleID = value; invalidatedListAll =  _changed;}
		}
		
		public string FieldTitle
		{
			get{ return fieldTitle != null ?fieldTitle.TrimEnd() : null; }
			set{ _changed |= fieldTitle != value; fieldTitle = value; invalidatedListAll =  _changed;}
		}
		
		public bool Visible
		{
			get{ return visible; }
			set{ _changed |= visible != value; visible = value; invalidatedListAll =  _changed;}
		}
		
		public int FieldOrder
		{
			get{ return fieldOrder; }
			set{ _changed |= fieldOrder != value; fieldOrder = value; invalidatedListAll =  _changed;}
		}
		
		public string FieldType
		{
			get{ return fieldType != null ?fieldType.TrimEnd() : null; }
			set{ _changed |= fieldType != value; fieldType = value; invalidatedListAll =  _changed;}
		}
		
	
		// generate a static property to retrieve all instances of a class that are stored in the database
		static public IList ListAll
		{
			get 
			{ 
				if( listAllCache == null || invalidatedListAll )
				{
					listAllCache = Broker.RetrieveList( typeof(rb_UserDefinedFields) ) as ArrayList;
					invalidatedListAll = false;
				}
				return listAllCache;
			}
		}
		
		#endregion

		#region Debug Properties
		/// <summary>
		/// Generated only when genDebug flag enabled in MyGeneration template UI
		/// Returns number of items in internal cache
		/// </summary>
		public static int CacheCount
		{
			get{ return listAllCache == null ? 0 : listAllCache.Count;}
		}
		
		#endregion

		#region Storage and retrieval
	   
		public static rb_UserDefinedFields Retrieve(int id )
		{
	   
			// Return null if id is smaller than seed and/or increment for autokey
			if(id<0) 
			{
				return null;
			}
		  
			Key key = new Key( typeof(rb_UserDefinedFields), true, "UserDefinedFieldID", id );
			return Broker.RetrieveInstance( typeof(rb_UserDefinedFields), key ) as rb_UserDefinedFields;
		}

		//Gentle.NET Business Entity script: Generation of complex retrieve function (multiple primary keys) is not implemented yet.

		public override void Persist()
		{
			if( Changed || !IsPersisted )
			{
				base.Persist();
				_changed=false;
			}
		}

		public override void Remove()
		{
			base.Remove();
			invalidatedListAll = true;
		}
		#endregion

		#region Relations
		// List of primary keys for this class table
		// Key: UserDefinedFieldID
		// List of foreign keys for this class table
		// Key: FK_UserDefinedData_UserDefinedFields primary table: rb_UserDefinedFields primary column: UserDefinedFieldID foreign column: UserDefinedFieldID foreign table: rb_UserDefinedData
		// Key: FK_UserDefinedFields_Modules primary table: rb_Modules primary column: ModuleID foreign column: ModuleID foreign table: rb_UserDefinedFields
		// List of selected relation tables for this database
		// Table: rb_Announcements
		// Table: rb_Announcements_st
		// Table: rb_Articles
		// Table: rb_Blacklist
		// Table: rb_BlogComments
		// Table: rb_Blogs
		// Table: rb_BlogStats
		// Table: rb_BookList
		// Table: rb_ComponentModule
		// Table: rb_Contacts
		// Table: rb_Contacts_st
		// Table: rb_ContentManager
		// Table: rb_Countries
		// Table: rb_Cultures
		// Table: rb_Discussion
		// Table: rb_Documents
		// Table: rb_Documents_st
		// Table: rb_EnhancedHtml
		// Table: rb_EnhancedHtml_st
		// Table: rb_EnhancedLinks
		// Table: rb_EnhancedLinks_st
		// Table: rb_Events
		// Table: rb_Events_st
		// Table: rb_FAQs
		// Table: rb_GeneralModuleDefinitions
		// Table: rb_HtmlText
		// Table: rb_HtmlText_st
		// Table: rb_Links
		// Table: rb_Links_st
		// Table: rb_Localize
		// Table: rb_Milestones
		// Table: rb_Milestones_st
		// Table: rb_ModuleDefinitions
		// Table: rb_Modules
		// Table: rb_ModuleSettings
		// Table: rb_Monitoring
		// Table: rb_Pictures
		// Table: rb_Pictures_st
		// Table: rb_Portals
		// Table: rb_PortalSettings
		// Table: rb_Roles
		// Table: rb_SolutionModuleDefinitions
		// Table: rb_Solutions
		// Table: rb_States
		// Table: rb_SurveyAnswers
		// Table: rb_SurveyOptions
		// Table: rb_SurveyQuestions
		// Table: rb_Surveys
		// Table: rb_Tabs
		// Table: rb_TabSettings
		// Table: rb_Tasks
		// Table: rb_UserDefinedData
		// Table: rb_UserDefinedFields
		// Table: rb_UserDefinedRows
		// Table: rb_UserDesktop
		// Table: rb_UserRoles
		// Table: rb_Users
		// Table: rb_Versions

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserDefinedRows", using relation table "rb_UserDefinedData"
		/// </summary>
		public IList referencedrb_UserDefinedRows()
		{
			return new GentleList( typeof(rb_UserDefinedRows), this, typeof(rb_UserDefinedData));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserDefinedData", using relation table "rb_UserDefinedFields"
		/// </summary>
		public IList referencedrb_UserDefinedData()
		{
			return new GentleList( typeof(rb_UserDefinedData), this, typeof(rb_UserDefinedFields));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_Modules", using relation table "rb_UserDefinedFields"
		/// </summary>
		public IList referencedrb_Modules()
		{
			return new GentleList( typeof(rb_Modules), this, typeof(rb_UserDefinedFields));
		}
		#endregion

		#region ManualCode
/***PRESERVE_BEGIN MANUAL_CODE***//***PRESERVE_END MANUAL_CODE***/
		#endregion
	}

}
#endregion


