
		
//========================================================================
// This file was generated using the MyGeneration tool in combination
// with the Gentle.NET Business Entity template, $Rev: 44 $
//========================================================================
using System;
using System.Collections;
using Gentle.Framework;

namespace Rainbow.Data.GentleNET
{
	#region rb_UserDefinedData
	/// <summary>
	/// This object represents the properties and methods of a Employee.
	/// </summary>
	[Serializable]
	[TableName("rb_UserDefinedData")]
	public class rb_UserDefinedData : Persistent
	{
		#region Members
		private bool _changed = false;
		private static bool invalidatedListAll = true;
		private static ArrayList listAllCache = null;
		[TableColumn("UserDefinedDataID", NotNull=true), PrimaryKey(AutoGenerated=true)]
		protected int userDefinedDataID;
		[TableColumn("UserDefinedFieldID", NotNull=true), ForeignKey("rb_UserDefinedFields", "UserDefinedFieldID")]
		protected int userDefinedFieldID;
		[TableColumn("UserDefinedRowID", NotNull=true), ForeignKey("rb_UserDefinedRows", "UserDefinedRowID")]
		protected int userDefinedRowID;
		[TableColumn("FieldValue", NotNull=true)]
		protected string fieldValue;
		#endregion
			

		#region Constructors
	

		/// <summary> 
		/// Create a new object by specifying all fields (except the auto-generated primary key field). 
		/// </summary> 
		public rb_UserDefinedData( 
				int UserDefinedFieldID, 
				int UserDefinedRowID, 
				string FieldValue)
		{
			_changed = true;
			invalidatedListAll = true;
			userDefinedFieldID = UserDefinedFieldID;
			userDefinedRowID = UserDefinedRowID;
			fieldValue = FieldValue;
		}

			
		/// <summary> 
		/// Create an object from an existing row of data. This will be used by Gentle to 
		/// construct objects from retrieved rows. 
		/// </summary> 
		public rb_UserDefinedData( 
				int UserDefinedDataID, 
				int UserDefinedFieldID, 
				int UserDefinedRowID, 
				string FieldValue)
		{
			userDefinedDataID = UserDefinedDataID;
			userDefinedFieldID = UserDefinedFieldID;
			userDefinedRowID = UserDefinedRowID;
			fieldValue = FieldValue;
		}

		#endregion

		#region Public Properties
		
		public bool Changed
		{ get { return _changed; } }
		
		public int UserDefinedDataID
		{
			get{ return userDefinedDataID; }
		}
		
		public int UserDefinedFieldID
		{
			get{ return userDefinedFieldID; }
			set{ _changed |= userDefinedFieldID != value; userDefinedFieldID = value; invalidatedListAll =  _changed;}
		}
		
		public int UserDefinedRowID
		{
			get{ return userDefinedRowID; }
			set{ _changed |= userDefinedRowID != value; userDefinedRowID = value; invalidatedListAll =  _changed;}
		}
		
		public string FieldValue
		{
			get{ return fieldValue != null ?fieldValue.TrimEnd() : null; }
			set{ _changed |= fieldValue != value; fieldValue = value; invalidatedListAll =  _changed;}
		}
		
	
		// generate a static property to retrieve all instances of a class that are stored in the database
		static public IList ListAll
		{
			get 
			{ 
				if( listAllCache == null || invalidatedListAll )
				{
					listAllCache = Broker.RetrieveList( typeof(rb_UserDefinedData) ) as ArrayList;
					invalidatedListAll = false;
				}
				return listAllCache;
			}
		}
		
		#endregion

		#region Debug Properties
		/// <summary>
		/// Generated only when genDebug flag enabled in MyGeneration template UI
		/// Returns number of items in internal cache
		/// </summary>
		public static int CacheCount
		{
			get{ return listAllCache == null ? 0 : listAllCache.Count;}
		}
		
		#endregion

		#region Storage and retrieval
	   
		public static rb_UserDefinedData Retrieve(int id )
		{
	   
			// Return null if id is smaller than seed and/or increment for autokey
			if(id<0) 
			{
				return null;
			}
		  
			Key key = new Key( typeof(rb_UserDefinedData), true, "UserDefinedDataID", id );
			return Broker.RetrieveInstance( typeof(rb_UserDefinedData), key ) as rb_UserDefinedData;
		}

		//Gentle.NET Business Entity script: Generation of complex retrieve function (multiple primary keys) is not implemented yet.

		public override void Persist()
		{
			if( Changed || !IsPersisted )
			{
				base.Persist();
				_changed=false;
			}
		}

		public override void Remove()
		{
			base.Remove();
			invalidatedListAll = true;
		}
		#endregion

		#region Relations
		// List of primary keys for this class table
		// Key: UserDefinedDataID
		// List of foreign keys for this class table
		// Key: FK_UserDefinedData_UserDefinedFields primary table: rb_UserDefinedFields primary column: UserDefinedFieldID foreign column: UserDefinedFieldID foreign table: rb_UserDefinedData
		// Key: FK_UserDefinedData_UserDefinedRows primary table: rb_UserDefinedRows primary column: UserDefinedRowID foreign column: UserDefinedRowID foreign table: rb_UserDefinedData
		// List of selected relation tables for this database
		// Table: rb_Announcements
		// Table: rb_Announcements_st
		// Table: rb_Articles
		// Table: rb_Blacklist
		// Table: rb_BlogComments
		// Table: rb_Blogs
		// Table: rb_BlogStats
		// Table: rb_BookList
		// Table: rb_ComponentModule
		// Table: rb_Contacts
		// Table: rb_Contacts_st
		// Table: rb_ContentManager
		// Table: rb_Countries
		// Table: rb_Cultures
		// Table: rb_Discussion
		// Table: rb_Documents
		// Table: rb_Documents_st
		// Table: rb_EnhancedHtml
		// Table: rb_EnhancedHtml_st
		// Table: rb_EnhancedLinks
		// Table: rb_EnhancedLinks_st
		// Table: rb_Events
		// Table: rb_Events_st
		// Table: rb_FAQs
		// Table: rb_GeneralModuleDefinitions
		// Table: rb_HtmlText
		// Table: rb_HtmlText_st
		// Table: rb_Links
		// Table: rb_Links_st
		// Table: rb_Localize
		// Table: rb_Milestones
		// Table: rb_Milestones_st
		// Table: rb_ModuleDefinitions
		// Table: rb_Modules
		// Table: rb_ModuleSettings
		// Table: rb_Monitoring
		// Table: rb_Pictures
		// Table: rb_Pictures_st
		// Table: rb_Portals
		// Table: rb_PortalSettings
		// Table: rb_Roles
		// Table: rb_SolutionModuleDefinitions
		// Table: rb_Solutions
		// Table: rb_States
		// Table: rb_SurveyAnswers
		// Table: rb_SurveyOptions
		// Table: rb_SurveyQuestions
		// Table: rb_Surveys
		// Table: rb_Tabs
		// Table: rb_TabSettings
		// Table: rb_Tasks
		// Table: rb_UserDefinedData
		// Table: rb_UserDefinedFields
		// Table: rb_UserDefinedRows
		// Table: rb_UserDesktop
		// Table: rb_UserRoles
		// Table: rb_Users
		// Table: rb_Versions

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserDefinedFields", using relation table "rb_UserDefinedData"
		/// </summary>
		public IList referencedrb_UserDefinedFields()
		{
			return new GentleList( typeof(rb_UserDefinedFields), this, typeof(rb_UserDefinedData));
		}

		/// <summary>
		/// Return list of referenced objects from n:m relation with
		/// table "rb_UserDefinedRows", using relation table "rb_UserDefinedData"
		/// </summary>
		public IList referencedrb_UserDefinedRows()
		{
			return new GentleList( typeof(rb_UserDefinedRows), this, typeof(rb_UserDefinedData));
		}
		#endregion

		#region ManualCode
/***PRESERVE_BEGIN MANUAL_CODE***//***PRESERVE_END MANUAL_CODE***/
		#endregion
	}

}
#endregion


